/**
 * Shared Realtime invalidation payload types (browser + server).
 */

export type RealtimeInvalidationType =
  | 'note:created'
  | 'note:updated'
  | 'note:deleted'
  | 'thread:updated'
  | 'thread:deleted'
  | 'space:updated'
  | 'userMetadata:updated'
  | 'sync:batch';

/**
 * Optional changed-field snapshot so listeners can patch caches in place instead
 * of invalidating + refetching. Kept small and JSON-serializable for the broadcast
 * channel. Any field may be omitted; listeners fall back to a refetch when absent.
 */
export interface RealtimeNotePatch {
  title?: string | null;
  /** Canonical/processed note HTML. */
  content?: string | null;
  updatedAt?: string;
  spaceId?: string | null;
  threadIds?: string[];
  tags?: Array<{
    id: string;
    name: string;
    color?: string | null;
    category?: string | null;
    isSystem?: boolean;
    isAutoGenerated?: boolean | null;
    confidence?: number | null;
  }>;
}

export interface RealtimeInvalidationPayload {
  type: RealtimeInvalidationType;
  id?: string;
  /** Present on note:created / note:updated when the sender can patch in place. */
  note?: RealtimeNotePatch;
}

export function isRealtimeInvalidationPayload(value: unknown): value is RealtimeInvalidationPayload {
  if (!value || typeof value !== 'object') return false;
  const t = (value as RealtimeInvalidationPayload).type;
  return (
    t === 'note:created' ||
    t === 'note:updated' ||
    t === 'note:deleted' ||
    t === 'thread:updated' ||
    t === 'thread:deleted' ||
    t === 'space:updated' ||
    t === 'userMetadata:updated' ||
    t === 'sync:batch'
  );
}
