#!/bin/sh
#
# Post-commit hook: bump version from conventional commit messages.
# Install: cp scripts/git-hooks/post-commit .git/hooks/post-commit && chmod +x .git/hooks/post-commit
#

node scripts/bump-version.js
