import type { NoteType } from './common.js';

export interface Note {
  id: string;
  title: string | null;
  content: string;
  contentEncrypted: boolean;
  threadId: string;
  spaceId: string | null;
  simpleNoteId: number | null;
  noteType: NoteType;
  addedBy: string;
  isPublic: boolean;
  isFeatured: boolean;
  shareToken?: string | null;
  createdAt: string;
  updatedAt: string | null;
  lastVisited: string | null;
  /** Scripture translation (only for scripture notes) */
  version?: string;
  /** Resource title (only for resource notes) */
  resourceTitle?: string | null;
  /** Resource description (only for resource notes) */
  resourceDescription?: string | null;
  /** Resource image URL (only for resource notes) */
  resourceImage?: string | null;
}

export interface RecentNote {
  id: string;
  title: string;
  content: string;
  contentEncrypted: boolean;
  threadId: string;
  spaceId: string | null;
  simpleNoteId: number | null;
  isPublic: boolean;
  isFeatured: boolean;
  createdAt: string;
  updatedAt: string | null;
  lastUpdated: string;
}

export interface NoteThread {
  id: string;
  title: string;
  subtitle: string;
  color: string | null;
  isPublic: boolean;
  isPinned: boolean;
  createdAt: string;
  updatedAt: string | null;
  count: number;
}

export interface UserThread {
  id: string;
  title: string;
  color: string | null;
  isPublic: boolean;
  createdAt: string;
  updatedAt: string | null;
}

export interface NoteComment {
  id: string;
  content: string;
  createdAt: string;
  updatedAt: string | null;
}

export interface NoteTag {
  id: string;
  name: string;
  color: string | null;
  category: string | null;
  isSystem: boolean;
  isAutoGenerated: boolean;
  confidence: number | null;
}

export interface ReferencingNote {
  id: string;
  title: string | null;
  content: string;
  simpleNoteId: number | null;
  noteType: string;
  createdAt: string;
  updatedAt: string | null;
  resourceTitle: string | null;
  resourceDescription: string | null;
  resourceImage: string | null;
}

export interface NoteDetails {
  success: boolean;
  note: Note;
  threads: NoteThread[];
  allUserThreads: UserThread[];
  comments: NoteComment[];
  tags: NoteTag[];
  referencingNotes: ReferencingNote[];
}

export interface CreateNoteParams {
  content: string;
  title?: string;
  threadId?: string;
  noteType?: NoteType;
  spaceId?: string;
  scriptureReference?: string;
  scriptureVersion?: string;
  resourceUrl?: string;
  contentEncrypted?: boolean;
}

export interface CreateNoteResponse {
  success: string;
  note: Note;
  scriptureResults: unknown[];
}

export interface UpdateNoteContentParams {
  content: string;
  contentEncrypted?: boolean;
}

export interface UpdateNoteContentResponse {
  success: boolean;
  message: string;
}

export interface DeleteNoteResponse {
  success: string;
  noteId: string;
  threadId: string;
}

export interface NextIdResponse {
  nextNoteId: number;
  formattedId: string;
}
