export interface Tag {
  id: string;
  name: string;
  color: string | null;
  category: string | null;
  userId: string;
  isSystem: boolean;
  createdAt: string;
  updatedAt: string | null;
}

export interface CreateTagParams {
  name: string;
  color?: string;
  category?: string;
}

export interface CreateTagResponse {
  success: boolean;
  tag: Tag;
}

export interface DeleteTagResponse {
  success: boolean;
}

export interface AssignTagParams {
  noteId: string;
  tagId: string;
  isAutoGenerated?: boolean;
  confidence?: number;
}

export interface AssignTagResponse {
  success: boolean;
  message: string;
  relationId: string;
}

export interface RemoveTagParams {
  noteId: string;
  tagId: string;
}

export interface RemoveTagResponse {
  success: boolean;
}
