/**
 * One sermon as a draggable card — the board's and the calendar's shared unit.
 *
 * Two jobs in one control, which is why it is not simply a button: a click
 * opens it in the editor rail, a drag moves it in time. dnd-kit's activation
 * distance is what tells them apart, so a click never begins a drag and a drag
 * never lands as a click.
 */
import { useDraggable } from '@dnd-kit/core';
import type { SpaceCoverPickerColor } from '@/utils/space-cover';
import type { TeachingPlanSermon } from '../../../hooks/queries/useChurchTeachingPlan';
import ProtoSeriesPill from './ProtoSeriesPill';

export function PlannerCardBody({
  service,
  timeLabel,
  compact,
  seriesAccent = null,
}: {
  service: TeachingPlanSermon;
  timeLabel: string | null;
  /** Calendar chips have a day cell's width, not a column's. */
  compact?: boolean;
  /** The run's colour, for the mark beside its name. Null for a standalone week. */
  seriesAccent?: SpaceCoverPickerColor | null;
}) {
  return (
    <>
      {/* Compact chips clamp to two lines, which the marquee cannot reveal —
          it slides one line sideways. Only the single-line title marquees. */}
      <span
        className={`pds-list-title proto-planner-card__title${compact ? '' : ' proto-marquee'}`}
        title={service.title}
      >
        {compact ? service.title : <span>{service.title}</span>}
      </span>
      {compact ? null : (
        <span className="proto-caption proto-planner-card__meta">
          {/* Time first: a church with a morning and an evening sermon has two
              cards on one date, and without this they read as duplicates. */}
          {timeLabel ? `${timeLabel} · ` : ''}
          {service.reference || 'No passage yet'}
        </span>
      )}
      {service.seriesTitle ? (
        /* Caption weight, not a badge. The pill this replaced gave a series more
           visual weight than the sermon's own passage, which inverted the row:
           what you preach outranks which run it belongs to.

           The mark is not a glyph in that sense — it carries the run's colour,
           which is the thing a scan down a column is actually following. It
           replaced the card's tinted left border, which said the same thing in
           a place the eye never looks and at a weight that vanished against
           the canvas. */
        <span className="proto-caption proto-planner-card__series">
          <ProtoSeriesPill accent={seriesAccent} name={service.seriesTitle} />
        </span>
      ) : null}
    </>
  );
}

export default function PrototypePlannerCard({
  service,
  timeLabel,
  draggable,
  selected,
  compact,
  accent,
  onSelect,
}: {
  service: TeachingPlanSermon;
  timeLabel: string | null;
  draggable: boolean;
  selected: boolean;
  compact?: boolean;
  /**
   * The series' colour, or null for a standalone sermon.
   *
   * A rail on the leading edge, never a badge. The pill this replaced was
   * removed because it outweighed the sermon's own passage (see PlannerCardBody
   * above), and the fix for "a series is invisible" must not reintroduce the
   * thing that made it too visible. Structure, not a label — and the caption
   * line stays, so the series is still named for anyone who cannot use colour.
   */
  accent?: SpaceCoverPickerColor | null;
  onSelect: () => void;
}) {
  const { attributes, listeners, setNodeRef, isDragging } = useDraggable({
    id: service.id,
    disabled: !draggable,
  });

  /*
    A week with nothing written into it yet — which is exactly what the "N to
    fill" count on a series measures, and now what the hollow date tile marks
    on the list surfaces. One test everywhere, so a week cannot look unfinished
    in the list and finished on the board.

    Deliberately "no passage", not "generated by Add weeks". The stricter test
    — still carrying the series' own name — is about *removal*, where it keeps
    "remove empty weeks" off work someone has done. For display, a week you
    titled but have not given a passage is just as unwritten as one you never
    touched, and a pastor scanning for what needs work wants to see both.
  */
  const placeholder = !service.reference;

  return (
    <button
      ref={setNodeRef}
      type="button"
      data-series-accent={accent ?? undefined}
      data-in-series={accent ? 'true' : undefined}
      className={[
        'proto-planner-card',
        /* The pointer lands on the card, not on the 100px of title, so the card
           is what triggers the title's marquee. */
        'proto-marquee-hover-root',
        /* Still clickable when read-only — the editor opens to be read — but a
           grab cursor would promise a drag that will not start. */
        draggable ? '' : 'proto-planner-card--static',
        compact ? 'proto-planner-card--compact' : '',
        placeholder ? 'proto-planner-card--placeholder' : '',
        selected ? 'proto-planner-card--selected' : '',
        /* Left in place but faded while the DragOverlay carries the real card —
           removing it would collapse the column and make the drop target move
           out from under the cursor. */
        isDragging ? 'proto-planner-card--dragging' : '',
      ]
        .filter(Boolean)
        .join(' ')}
      onClick={onSelect}
      {...listeners}
      {...attributes}
    >
      <PlannerCardBody
        service={service}
        timeLabel={timeLabel}
        compact={compact}
        seriesAccent={accent ?? null}
      />
    </button>
  );
}
