export const NOTE_HISTORY_COPY = {
  menuItem: 'History',
  title: 'History',
  close: 'Close history',
  current: 'Current version',
  empty: 'No earlier versions yet.',
  loadError: 'Could not load history',
  retry: 'Try again',
  loadMore: 'Show older',
  lockedTitle: 'Older history',
  lockedMeta: (date: string) => `Versions before ${date} are kept. See them with Harvous Plus.`,
  encryptedRow: 'Locked version',
  encryptedPreview: 'This version was locked with your PIN, so it can’t be shown here.',
  previewPrompt: 'Pick a version to see it here.',
  previewError: 'Could not load this version',
  untitled: 'Untitled',
  back: 'All versions',
  restore: 'Restore',
  cancel: 'Cancel',
  restoreConfirmTitle: 'Restore this version?',
  restoreConfirmBody: (date: string) =>
    `Your note will go back to how it looked on ${date}. What’s there now stays in history.`,
  restored: (date: string) => `Restored the version from ${date}`,
  undo: 'Undo',
  conflict: 'This note changed somewhere else. Reopen History and try again.',
  restoreError: 'Could not restore this version',
  saves: (count: number) => (count === 1 ? '1 save' : `${count} saves`),
} as const;
