import type { APIRoute } from 'astro';
import { db, Tags, NoteTags, eq, and } from 'astro:db';

export const POST: APIRoute = async ({ request, locals }) => {
  try {
    const { userId } = locals.auth();
    
    if (!userId) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    const body = await request.json();
    const { noteId, tagId, isAutoGenerated = false, confidence } = body;

    if (!noteId || !tagId) {
      return new Response(JSON.stringify({ error: 'Note ID and Tag ID are required' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // Check if tag exists and belongs to user
    const tag = await db
      .select()
      .from(Tags)
      .where(and(eq(Tags.id, tagId), eq(Tags.userId, userId)))
      .get();

    if (!tag) {
      return new Response(JSON.stringify({ error: 'Tag not found' }), {
        status: 404,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // Check if relationship already exists
    const existingRelation = await db
      .select()
      .from(NoteTags)
      .where(and(eq(NoteTags.noteId, noteId), eq(NoteTags.tagId, tagId)))
      .get();

    if (existingRelation) {
      return new Response(JSON.stringify({ error: 'Tag already assigned to note' }), {
        status: 409,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // Create note-tag relationship
    const relationId = `note_tag_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    
    await db.insert(NoteTags).values({
      id: relationId,
      noteId: noteId,
      tagId: tagId,
      isAutoGenerated: isAutoGenerated,
      confidence: confidence,
      createdAt: new Date(),
    });

    return new Response(JSON.stringify({ 
      success: true, 
      message: 'Tag assigned to note successfully',
      relationId: relationId
    }), {
      status: 201,
      headers: { 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('Error assigning tag to note:', error);
    return new Response(JSON.stringify({ error: 'Internal server error' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
};
