import type { APIRoute } from 'astro';
import { db, Tags, NoteTags, eq, and } from 'astro:db';

export const GET: APIRoute = async ({ locals, url }) => {
  try {
    const { userId } = locals.auth();
    
    if (!userId) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    const noteId = url.searchParams.get('noteId');

    if (!noteId) {
      return new Response(JSON.stringify({ error: 'Note ID is required' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // Get all tags for the note
    const noteTags = await db
      .select({
        id: NoteTags.id,
        noteId: NoteTags.noteId,
        tagId: NoteTags.tagId,
        isAutoGenerated: NoteTags.isAutoGenerated,
        confidence: NoteTags.confidence,
        createdAt: NoteTags.createdAt,
        tag: {
          id: Tags.id,
          name: Tags.name,
          color: Tags.color,
          category: Tags.category,
          isSystem: Tags.isSystem
        }
      })
      .from(NoteTags)
      .innerJoin(Tags, eq(NoteTags.tagId, Tags.id))
      .where(and(eq(NoteTags.noteId, noteId), eq(Tags.userId, userId)));

    return new Response(JSON.stringify({ 
      success: true, 
      tags: noteTags 
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('Error fetching note tags:', error);
    return new Response(JSON.stringify({ error: 'Internal server error' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
};
