/**
 * GET /api/about/founder-letter
 *
 * Returns the founder letter as rendered HTML.
 * Content comes from founder-letter.inline.generated.ts (generated by
 * scripts/generate-founder-letter.js from src/data/about/founder-letter.md)
 * so it is bundled into api.cjs and loads in both dev and production/PWA.
 */

import { Hono } from 'hono';
import { markdownToHtml } from '@/utils/markdown-to-html';
import founderLetterMarkdown from './founder-letter.inline';

const route = new Hono();

route.get('/api/about/founder-letter', async (c) => {
  const html = markdownToHtml(founderLetterMarkdown);
  return c.json(
    { html },
    200,
    { 'Cache-Control': 'public, max-age=86400' },
  );
});

export default route;
