/**
 * Resource Notes routes — Hono port of src/pages/api/resource/*.ts
 *
 * Endpoints:
 *   POST /api/resource/:id/update-image
 *   POST /api/resource/check-duplicate
 *   POST /api/resource/metadata
 *   POST /api/resource/suggest-threads
 *   POST /api/resource/update-metadata
 */

import { Hono } from 'hono';
import { getAuthenticatedAuth, requireAuth, requireParam } from '../middleware/auth';
import { db, first, ResourceMetadata, Notes, NoteThreads, Threads, eq, and, inArray } from '../db';
import { handleAPIError } from '@/utils/error-handling';
import { rateLimit } from '@/utils/rate-limit';
import { validateResourceUrl, extractDomain, getDomainFriendlyName, normalizeUrl } from '@/utils/validation';
import { extractArticleContent } from '@/utils/content-extractor';

const app = new Hono();

// ─── Helpers (inlined from metadata endpoint) ───────────────────────

function decodeHtmlEntities(text: string): string {
  const entities: Record<string, string> = { '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&#39;': "'", '&apos;': "'", '&nbsp;': ' ' };
  return text.replace(/&[#\w]+;/g, (entity) => entities[entity] || entity);
}

function isGenericImage(imageUrl: string): boolean {
  if (!imageUrl) return true;
  const lowerUrl = imageUrl.toLowerCase();
  const genericPatterns = ['logo','default','banner','header','og-image','ogimage','social-share','share-image','site-image','favicon','placeholder','thumbnail-default','brand','icon','/social/','/og/','/share/','/opengraph/','social-media','meta-image','featured-default','/static/images/','/assets/images/social','1200x630','1200x600','1200x628','600x315','twitter-card','facebook-share','linkedin-share'];
  if (genericPatterns.some(p => lowerUrl.includes(p))) return true;
  const filename = lowerUrl.split('/').pop()?.split('?')[0] || '';
  if (filename.length < 10 && !filename.includes('-') && !filename.includes('_')) return true;
  const pathParts = lowerUrl.split('/');
  const hasContentSpecificPath = pathParts.some(part => /^\d{4}$/.test(part) || /^[a-z]+-[a-z]+-[a-z]+/.test(part) || part.includes('article') || part.includes('post') || part.includes('guide'));
  if (!hasContentSpecificPath && (lowerUrl.includes('/static/') || lowerUrl.includes('/assets/'))) return true;
  return false;
}

function extractFirstContentImage(html: string, baseUrl: string): string | null {
  const imgPattern = /<img[^>]+src=["']([^"']+)["'][^>]*>/gi;
  const images: string[] = [];
  let match;
  while ((match = imgPattern.exec(html)) !== null) {
    const src = match[1];
    const fullMatch = match[0].toLowerCase();
    if (fullMatch.includes('width="1"') || fullMatch.includes("width='1'") || fullMatch.includes('height="1"') || fullMatch.includes("height='1'") || fullMatch.includes('icon') || fullMatch.includes('avatar') || fullMatch.includes('emoji') || fullMatch.includes('pixel') || fullMatch.includes('tracking') || fullMatch.includes('spacer') || fullMatch.includes('badge') || src.includes('data:image') || src.includes('.svg') || src.includes('gravatar')) continue;
    if (isGenericImage(src)) continue;
    images.push(src);
  }
  if (images.length > 0) {
    let imageUrl = images[0];
    if (!imageUrl.startsWith('http')) { try { imageUrl = new URL(imageUrl, baseUrl).href; } catch { return null; } }
    return imageUrl;
  }
  return null;
}

function extractSiteNameFromTitle(title: string): string | null {
  if (!title) return null;
  const parts = title.trim().split(/\s*[\|–—\-·]\s*/);
  if (parts.length >= 2) { const lastPart = parts[parts.length - 1].trim(); if (lastPart.length > 0 && lastPart.length < 30) return lastPart; }
  return null;
}

function cleanTitle(title: string): string {
  if (!title) return '';
  let cleaned = title.trim();
  const separatorCount = (cleaned.match(/[\|–—]/g) || []).length;
  if (separatorCount === 1) { const suffixPattern = /\s*[\|–—\-]\s*[^|\-–—]+$/; const match = cleaned.match(suffixPattern); if (match && match[0].length < cleaned.length * 0.3) cleaned = cleaned.replace(suffixPattern, '').trim(); }
  cleaned = cleaned.replace(/\s*-\s*YouTube\s*$/i, '').trim();
  return cleaned;
}

function stripAutoGeneratedParts(filename: string): string {
  if (!filename) return '';
  let cleaned = filename.trim();
  cleaned = cleaned.replace(/\b[0-9a-f]{8}[- ]?[0-9a-f]{4}[- ]?[0-9a-f]{4}[- ]?[0-9a-f]{4}[- ]?[0-9a-f]{12}\b/gi, '');
  cleaned = cleaned.replace(/\b[0-9a-f]{32,}\b/gi, '');
  return cleaned.replace(/\s+/g, ' ').trim();
}

// ─── Endpoints ──────────────────────────────────────────────────────

/** POST /api/resource/:id/update-image */
app.post('/api/resource/:id/update-image', requireAuth, rateLimit('write'), async (c) => {
  try {
    const auth = getAuthenticatedAuth(c);

    const id = requireParam(c, 'id');
    const { image } = await c.req.json();

    const existingNote = first(await db.select().from(Notes).where(and(eq(Notes.id, id), eq(Notes.userId, auth.userId))).limit(1));
    if (!existingNote) return c.json({ error: 'Note not found or access denied' }, 404);
    if (existingNote.noteType !== 'resource') return c.json({ error: 'Note is not a resource note' }, 400);

    const resourceMeta = first(await db.select().from(ResourceMetadata).where(eq(ResourceMetadata.noteId, id)).limit(1));
    if (!resourceMeta) return c.json({ error: 'Resource metadata not found' }, 404);

    await db.update(ResourceMetadata).set({ sourceImage: image || null }).where(eq(ResourceMetadata.noteId, id));

    return c.json({ success: true, message: 'Resource image updated' });
  } catch (error) {
    const standardError = handleAPIError(error, { endpoint: '/api/resource/[id]/update-image', action: 'update_resource_image' });
    return c.json({ error: standardError.message, code: standardError.code }, 500);
  }
});

/** POST /api/resource/check-duplicate */
app.post('/api/resource/check-duplicate', requireAuth, async (c) => {
  try {
    const auth = getAuthenticatedAuth(c);

    const { url } = await c.req.json();
    if (!url || typeof url !== 'string') return c.json({ error: 'URL is required', code: 'MISSING_URL' }, 400);

    const urlValidation = validateResourceUrl(url);
    if (!urlValidation.isValid) return c.json({ error: urlValidation.error || 'Invalid URL', code: urlValidation.code || 'INVALID_URL' }, 400);

    const normalizedUrl = urlValidation.normalizedUrl!;

    const existingResources = await db
      .select({ noteId: ResourceMetadata.noteId, sourceUrl: ResourceMetadata.sourceUrl, sourceTitle: ResourceMetadata.sourceTitle, sourceDescription: ResourceMetadata.sourceDescription, sourceImage: ResourceMetadata.sourceImage, noteTitle: Notes.title, simpleNoteId: Notes.simpleNoteId })
      .from(ResourceMetadata)
      .innerJoin(Notes, eq(ResourceMetadata.noteId, Notes.id))
      .where(and(eq(ResourceMetadata.sourceUrl, normalizedUrl), eq(Notes.userId, auth.userId)))
      .limit(1);

    if (existingResources.length > 0) {
      const existing = existingResources[0];
      return c.json({ exists: true, noteId: existing.noteId, simpleNoteId: existing.simpleNoteId, title: existing.sourceTitle || existing.noteTitle || 'Untitled Resource', description: existing.sourceDescription || null, image: existing.sourceImage || null, url: existing.sourceUrl });
    }

    return c.json({ exists: false });
  } catch (error) {
    console.error('Error checking for duplicate resource:', error);
    return c.json({ error: 'Failed to check for duplicates', code: 'CHECK_FAILED' }, 500);
  }
});

/** POST /api/resource/metadata */
app.post('/api/resource/metadata', async (c) => {
  try {
    const body = await c.req.json();
    const { url, metadata, extractContent } = body;

    if (metadata && typeof metadata === 'object') {
      return c.json({
        success: true,
        metadata: { title: metadata.title || metadata.ogTitle || '', description: metadata.description || metadata.ogDescription || '', image: metadata.image || metadata.ogImage || '', url: url || metadata.url || '', siteName: metadata.siteName || metadata.ogSiteName || null },
      });
    }

    if (!url || typeof url !== 'string') return c.json({ error: 'URL is required', code: 'MISSING_URL' }, 400);

    const urlValidation = validateResourceUrl(url);
    if (!urlValidation.isValid) return c.json({ error: urlValidation.error || 'Invalid URL', code: urlValidation.code || 'INVALID_URL' }, 400);

    const normalizedUrl = urlValidation.normalizedUrl!;
    const isPDF = urlValidation.isPDF || false;

    let parsedUrl: URL;
    try { parsedUrl = new URL(normalizedUrl); } catch { return c.json({ error: 'Invalid URL format', code: 'INVALID_URL' }, 400); }

    if (isPDF) {
      const urlPath = parsedUrl.pathname;
      let filename = 'PDF Document';
      const lastSegment = urlPath.split('/').filter(Boolean).pop();
      if (lastSegment) {
        let decodedFilename = decodeURIComponent(lastSegment).replace(/\.pdf$/i, '').replace(/[-_]/g, ' ').trim();
        decodedFilename = stripAutoGeneratedParts(decodedFilename);
        if (decodedFilename && decodedFilename.length > 0) {
          filename = decodedFilename.split(' ').filter(w => w.length > 0).map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(' ');
        }
      }
      if (!filename || filename.trim().length === 0) filename = 'PDF Document';
      return c.json({ success: true, metadata: { title: filename, description: 'PDF Document', image: '', url: normalizedUrl, siteName: parsedUrl.hostname.replace('www.', ''), contentType: 'pdf' } });
    }

    const response = await fetch(normalizedUrl, {
      headers: { 'User-Agent': 'Mozilla/5.0 (compatible; HarvousBot/1.0; +https://harvous.com)', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' },
      signal: AbortSignal.timeout(10000),
    });

    if (!response.ok) return c.json({ error: `Failed to fetch URL: ${response.statusText}`, code: 'FETCH_ERROR', status: response.status }, response.status >= 500 ? 502 : 400);

    const html = await response.text();

    const ogTitleMatch = html.match(/<meta\s+(?:property|name)=["']?og:title["']?\s+content=["']([^"']+)["']/i) || html.match(/<meta\s+content=["']([^"']+)["']\s+(?:property|name)=["']?og:title["']?/i);
    const ogDescriptionMatch = html.match(/<meta\s+(?:property|name)=["']?og:description["']?\s+content=["']([^"']+)["']/i) || html.match(/<meta\s+content=["']([^"']+)["']\s+(?:property|name)=["']?og:description["']?/i);
    const ogImageMatch = html.match(/<meta\s+(?:property|name)=["']?og:image["']?\s+content=["']([^"']+)["']/i) || html.match(/<meta\s+content=["']([^"']+)["']\s+(?:property|name)=["']?og:image["']?/i);
    const ogSiteNameMatch = html.match(/<meta\s+(?:property|name)=["']?og:site_name["']?\s+content=["']([^"']+)["']/i) || html.match(/<meta\s+content=["']([^"']+)["']\s+(?:property|name)=["']?og:site_name["']?/i);

    const pageTitleMatch = html.match(/<title[^>]*>([^<]+)<\/title>/i);
    const h1Match = html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
    const h2Match = html.match(/<h2[^>]*>([\s\S]*?)<\/h2>/i);
    const stripHtmlTags = (str: string) => str.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();

    const isVideoSite = parsedUrl.hostname.includes('youtube.com') || parsedUrl.hostname.includes('youtu.be') || parsedUrl.hostname.includes('vimeo.com');

    let bestTitle = '';
    if (isVideoSite) {
      if (ogTitleMatch?.[1]?.trim()) bestTitle = cleanTitle(decodeHtmlEntities(ogTitleMatch[1].trim()));
      if (!bestTitle && pageTitleMatch?.[1]?.trim()) bestTitle = cleanTitle(decodeHtmlEntities(pageTitleMatch[1].trim()));
    } else {
      if (h1Match?.[1]) { const t = stripHtmlTags(h1Match[1]); if (t) bestTitle = decodeHtmlEntities(t); }
      if (!bestTitle && pageTitleMatch?.[1]?.trim()) bestTitle = cleanTitle(decodeHtmlEntities(pageTitleMatch[1].trim()));
      if (!bestTitle && h2Match?.[1]) { const t = stripHtmlTags(h2Match[1]); if (t) bestTitle = decodeHtmlEntities(t); }
      if (!bestTitle && ogTitleMatch?.[1]?.trim()) bestTitle = cleanTitle(decodeHtmlEntities(ogTitleMatch[1].trim()));
    }

    const descriptionMatch = ogDescriptionMatch || html.match(/<meta\s+name=["']?description["']?\s+content=["']([^"']+)["']/i) || html.match(/<meta\s+content=["']([^"']+)["']\s+name=["']?description["']?/i);

    let imageUrl = '';
    const contentImage = extractFirstContentImage(html, parsedUrl.origin);
    if (contentImage) imageUrl = contentImage;
    if (!imageUrl && ogImageMatch) {
      imageUrl = ogImageMatch[1];
      if (imageUrl && !imageUrl.startsWith('http')) { try { imageUrl = new URL(imageUrl, parsedUrl.origin).href; } catch { imageUrl = ''; } }
    }

    let siteName: string | null = ogSiteNameMatch ? decodeHtmlEntities(ogSiteNameMatch[1].trim()) : null;
    if (!siteName && bestTitle) siteName = extractSiteNameFromTitle(bestTitle);
    if (!siteName) {
      const domain = extractDomain(normalizedUrl);
      if (domain) {
        const friendlyName = getDomainFriendlyName(domain);
        if (friendlyName && friendlyName !== domain) siteName = friendlyName;
        else siteName = domain.replace(/\.(com|org|net|io|co|edu|gov)$/i, '').split(/[.\-]/).map(p => p.charAt(0).toUpperCase() + p.slice(1)).join(' ');
      }
    }

    const extractedMetadata: any = { title: bestTitle, description: descriptionMatch ? decodeHtmlEntities(descriptionMatch[1].trim()) : '', image: imageUrl, url: normalizedUrl, siteName };
    if (extractContent === true) {
      try { extractedMetadata.articleContent = await extractArticleContent(html, normalizedUrl); } catch (e) { console.error('Error extracting article content:', e); }
    }

    return c.json({ success: true, metadata: extractedMetadata });
  } catch (error: any) {
    if (error.name === 'AbortError' || error.name === 'TimeoutError') {
      return c.json({ error: 'Request timeout - URL took too long to respond', code: 'TIMEOUT' }, 504);
    }
    const standardError = handleAPIError(error, { endpoint: '/api/resource/metadata', action: 'fetch_resource_metadata' });
    return c.json({ error: standardError.message, code: standardError.code }, 500);
  }
});

/** POST /api/resource/suggest-threads */
app.post('/api/resource/suggest-threads', requireAuth, async (c) => {
  try {
    const auth = getAuthenticatedAuth(c);

    const { resourceUrl, sourceName } = await c.req.json();
    if (!resourceUrl || typeof resourceUrl !== 'string') return c.json({ error: 'Resource URL is required', code: 'MISSING_URL' }, 400);

    const urlValidation = validateResourceUrl(resourceUrl);
    if (!urlValidation.isValid || !urlValidation.normalizedUrl) return c.json({ error: urlValidation.error || 'Invalid URL', code: urlValidation.code || 'INVALID_URL' }, 400);

    const domain = extractDomain(urlValidation.normalizedUrl);
    if (!domain) return c.json({ error: 'Could not extract domain from URL', code: 'DOMAIN_EXTRACTION_FAILED' }, 400);

    const matchingResources = await db
      .select({ noteId: ResourceMetadata.noteId, sourceName: ResourceMetadata.sourceName })
      .from(ResourceMetadata)
      .innerJoin(Notes, eq(ResourceMetadata.noteId, Notes.id))
      .where(and(eq(ResourceMetadata.sourceDomain, domain), eq(Notes.userId, auth.userId)))
      ;

    let suggestedThreadName: string | null = null;
    if (sourceName && typeof sourceName === 'string' && sourceName.trim() !== '') suggestedThreadName = sourceName.trim();
    if (!suggestedThreadName && matchingResources.length > 0) {
      const sourceNames = matchingResources.map(r => r.sourceName).filter((n): n is string => n !== null && n.trim() !== '');
      if (sourceNames.length > 0) {
        const nameCounts: Record<string, number> = {};
        sourceNames.forEach(n => { nameCounts[n] = (nameCounts[n] || 0) + 1; });
        suggestedThreadName = Object.entries(nameCounts).sort((a, b) => b[1] - a[1])[0][0];
      }
    }
    if (!suggestedThreadName) {
      const friendlyName = getDomainFriendlyName(domain);
      suggestedThreadName = friendlyName || domain.charAt(0).toUpperCase() + domain.slice(1).replace(/\./g, ' ');
    }

    if (matchingResources.length === 0) {
      return c.json({ success: true, suggestedThreadIds: [], suggestedThreadName, domain });
    }

    const noteIds = matchingResources.map(r => r.noteId);
    const threadRelations = await db.select({ threadId: NoteThreads.threadId }).from(NoteThreads).where(inArray(NoteThreads.noteId, noteIds));
    const uniqueThreadIds = [...new Set(threadRelations.map(r => r.threadId))].filter(id => id !== 'thread_unorganized');

    if (uniqueThreadIds.length === 0) {
      return c.json({ success: true, suggestedThreadIds: [], suggestedThreadName, domain });
    }

    const suggestedThreads = await db.select({ id: Threads.id, title: Threads.title, color: Threads.color }).from(Threads).where(and(inArray(Threads.id, uniqueThreadIds), eq(Threads.userId, auth.userId)));
    const matchingThreads = suggestedThreads.filter(t => suggestedThreadName && t.title.trim().toLowerCase() === suggestedThreadName.trim().toLowerCase());

    if (matchingThreads.length === 0) {
      return c.json({ success: true, suggestedThreadIds: [], suggestedThreads: [], suggestedThreadName, domain });
    }

    const threadNoteCounts = await Promise.all(matchingThreads.map(async (thread) => {
      const matchingNotesInThread = await db.select().from(NoteThreads).where(and(eq(NoteThreads.threadId, thread.id), inArray(NoteThreads.noteId, noteIds)));
      return { threadId: thread.id, count: matchingNotesInThread.length };
    }));

    const suggestedThreadIds = matchingThreads.map(thread => {
      const noteCount = threadNoteCounts.find(tc => tc.threadId === thread.id)?.count || 0;
      return { id: thread.id, title: thread.title, color: thread.color, noteCount };
    }).sort((a, b) => b.noteCount - a.noteCount);

    return c.json({ success: true, suggestedThreadIds: suggestedThreadIds.map(t => t.id), suggestedThreads: suggestedThreadIds, suggestedThreadName: null, domain });
  } catch (error) {
    const standardError = handleAPIError(error, { endpoint: '/api/resource/suggest-threads', action: 'suggest_threads' });
    return c.json({ error: standardError.message, code: standardError.code }, 500);
  }
});

/** POST /api/resource/update-metadata */
app.post('/api/resource/update-metadata', requireAuth, rateLimit('write'), async (c) => {
  try {
    const auth = getAuthenticatedAuth(c);

    const { noteId, image } = await c.req.json();
    if (!noteId) return c.json({ error: 'Note ID is required' }, 400);

    const existingNote = first(await db.select().from(Notes).where(and(eq(Notes.id, noteId), eq(Notes.userId, auth.userId))).limit(1));
    if (!existingNote) return c.json({ error: 'Note not found or access denied' }, 404);
    if (existingNote.noteType !== 'resource') return c.json({ error: 'Note is not a resource note' }, 400);

    const resourceMeta = first(await db.select().from(ResourceMetadata).where(eq(ResourceMetadata.noteId, noteId)).limit(1));
    if (!resourceMeta) return c.json({ error: 'Resource metadata not found' }, 404);

    await db.update(ResourceMetadata).set({ sourceImage: image || null }).where(eq(ResourceMetadata.noteId, noteId));

    return c.json({ success: true, message: 'Resource metadata updated' });
  } catch (error) {
    const standardError = handleAPIError(error, { endpoint: '/api/resource/update-metadata', action: 'update_resource_metadata' });
    return c.json({ error: standardError.message, code: standardError.code }, 500);
  }
});

export default app;
