import { useQuery, QueryClient } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { resolveNoteListPreview } from '@/utils/note-list-preview';

/** Thread context when seeding note cache from a list (thread/space page). */
export interface NoteSeedThreadContext {
  id: string;
  title: string;
  color: string | null;
  backgroundGradient: string;
}

/** List note shape from GET /api/threads/:id/notes (or similar). */
export interface ListNoteForSeed {
  id: string;
  title?: string | null;
  content?: string | null;
  contentEncrypted?: boolean;
  noteType?: string;
  threadId?: string;
  spaceId?: string | null;
  simpleNoteId?: number | null;
  createdAt?: string;
  updatedAt?: string;
  resourceTitle?: string | null;
  resourceDescription?: string | null;
  resourceImage?: string | null;
  userId?: string;
  version?: string;
  primaryCollection?: string | null;
  secondaryCollections?: string[];
  collectionPinned?: boolean;
  collectionUserOverride?: boolean;
  /** Shared space list seed — note belongs to the viewer. */
  isOwnNote?: boolean;
  /**
   * Length of the *stored* body (server NOTE_LIST_SELECT). Greater than
   * `content.length` means `content` is a truncated prefix. Absent on hand-built
   * seeds, in which case truncation can't be proven and isn't claimed.
   */
  contentLength?: number | null;
}

/** Slim linked-note row from GET /api/notes/:id/details (connections strip). */
export interface LinkedNoteRef {
  id: string;
  title?: string | null;
  noteType?: string;
  resourceTitle?: string | null;
  resourceDescription?: string | null;
  resourceImage?: string | null;
}

/** Study thread entry row from GET /api/notes/:id/details (mirrors `StudyThreadEntries` + native StudyThread fields). */
export interface StudyThreadEntryDetail {
  id: string;
  userId?: string;
  parentNoteId: string;
  spaceId: string | null;
  entryKind: string;
  highlightAccentRaw: string | null;
  sourceSnippet: string | null;
  focusTitle: string | null;
  notesBody: string | null;
  miniNoteBody: string | null;
  linkedNoteId: string | null;
  linkedNoteTitle: string | null;
  anchorLocation: number | null;
  anchorLength: number | null;
  anchorTextSnapshot: string | null;
  anchorQuote?: string | null;
  anchorPrefixContext?: string | null;
  anchorSuffixContext?: string | null;
  anchorStatus?: string | null;
  resolvedAnchorStart?: number | null;
  resolvedAnchorEnd?: number | null;
  anchorResolvedAt?: string | null;
  anchorDetachedAt?: string | null;
  scriptureReference: string | null;
  scripturePassageTranslation: string | null;
  scripturePassageExcerpt: string | null;
  isArchived: boolean;
  highlightListEditedAt: string | null;
  createdAt: string;
  updatedAt: string;
  /** Shared space unioned highlights only. */
  authorDisplayName?: string;
  authorColor?: string;
  isOwnHighlight?: boolean;
}

export interface NoteDetail {
  id: string;
  title: string | null;
  content: string | null;
  noteType: string;
  /** 'system' = onboarding seed notes; treat as read-only in the UI. */
  addedBy?: string;
  contentEncrypted: boolean;
  version?: string;
  /** Canonical optimistic-concurrency version, distinct from scripture translation. */
  currentVersion?: number;
  currentVersionId?: string | null;
  resourceTitle?: string | null;
  resourceDescription?: string | null;
  resourceImage?: string | null;
  resourceUrl?: string | null;
  simpleNoteId?: number | null;
  spaceId?: string | null;
  isPublic: boolean;
  shareToken?: string | null;
  userId?: string;
  /** Canonical author fields returned for a shared-context read. */
  authorUserId?: string;
  authorDisplayName?: string;
  authorColor?: string;
  contextSpaceId?: string;
  organization?: {
    isPinned: boolean;
    primaryCollection: string | null;
    secondaryCollections: string[];
    collectionPinned: boolean;
    order: number;
  } | null;
  /** Shared space list seed — note belongs to the viewer. */
  isOwnNote?: boolean;
  /** Author has opened this note for co-editing by its shared spaces. */
  coEditEnabled?: boolean;
  /**
   * The server's verdict on whether this viewer may write the body. Render from
   * this — never re-derive from role + flags, or the UI can drift from what the
   * write endpoint will actually accept.
   */
  canEdit?: boolean;
  /** Everyone who has saved a checkpoint of this note, author first. */
  contributors?: { userId: string; displayName: string; color: string }[];
  createdAt: string;
  updatedAt: string;
  threads: { id: string; title: string; color: string | null; backgroundGradient?: string }[];
  tags: {
    id: string;
    name: string;
    color?: string | null;
    category?: string | null;
    isSystem?: boolean;
    isAutoGenerated?: boolean | null;
    confidence?: number | null;
  }[];
  spaces?: { id: string; title: string; coEditEnabled?: boolean; spaceType?: string }[];
  linkedFromNoteId?: string | null;
  /** Template id applied to start/fill this note (`soap`, `ntpl_…`). */
  startedFromTemplateId?: string | null;
  /** Display name snapshot for template provenance. */
  startedFromTemplateName?: string | null;
  primaryCollection?: string | null;
  secondaryCollections?: string[];
  collectionPinned?: boolean;
  collectionUserOverride?: boolean;
  collectionLastAutoUpdatedAt?: string | null;
  /** Normalized auto-tag names the user dismissed on this note. */
  dismissedAutoTags?: string[];
  studyThreadTitle?: string | null;
  studyThreadUserOverride?: boolean;
  studyThreadPinned?: boolean;
  studyThreadLastAutoSuggestedAt?: string | null;
  linkedFromNotes?: LinkedNoteRef[];
  linkedToNotes?: LinkedNoteRef[];
  studyThreads?: StudyThreadEntryDetail[];
  /**
   * Internal: set when `content` was seeded from a list payload (server
   * NOTE_LIST_SELECT), which may be a truncated preview. Signals `useNote` to
   * treat the cached entry as stale so the full body is fetched on open. Cleared
   * once GET /api/notes/:id/details has populated the full detail.
   */
  __contentIsPreview?: boolean;
  /**
   * Internal: set when `content` is *provably* a prefix of the stored body — the note
   * is longer than the list cap. `__contentIsPreview` alone can't tell that apart from
   * a short note whose preview is the whole thing, and the editor needs the difference:
   * a truncated body must never be saved, or it overwrites the note with its own preview.
   */
  __contentTruncated?: boolean;
  /**
   * Internal: character offset into the stored content where a truncated `content` ends,
   * so the missing tail can be appended once the full body loads.
   */
  __previewLength?: number;
}

interface NoteDetailResponse {
  success: boolean;
  note: Omit<NoteDetail, 'threads' | 'tags' | 'spaces' | 'linkedFromNotes' | 'linkedToNotes' | 'studyThreads'>;
  threads: NoteDetail['threads'];
  tags?: NoteDetail['tags'];
  linkedFromNotes?: LinkedNoteRef[];
  linkedToNotes?: LinkedNoteRef[];
  studyThreads?: StudyThreadEntryDetail[];
  activeSharedAssociations?: Array<{
    spaceId: string;
    spaceTitle: string;
    spaceType?: string;
    coEditEnabled?: boolean;
  }>;
  context?: {
    spaceId: string;
    title: string;
    type: string;
    isShared: boolean;
    organization?: NoteDetail['organization'];
  };
  currentVersion?: { version: number; createdAt?: string } | number | null;
  currentVersionId?: string | null;
}

export function shouldUseNoteOnlyParentThreadCache(contextSpaceId?: string | null): boolean {
  return !contextSpaceId?.trim();
}

export function getCachedNoteParentThreadId(noteId: string): string | null {
  try { return localStorage.getItem(`harvous-note-thread-${noteId}`); } catch { return null; }
}

export interface CachedThread {
  id: string;
  title: string;
  noteCount: number;
  backgroundGradient: string;
  spaceId?: string | null;
}

export function getCachedNoteParentThread(noteId: string): CachedThread | null {
  try {
    const raw = localStorage.getItem(`harvous-note-thread-data-${noteId}`);
    return raw ? JSON.parse(raw) as CachedThread : null;
  } catch { return null; }
}

function setCachedNoteParentThread(noteId: string, thread: CachedThread) {
  try { localStorage.setItem(`harvous-note-thread-data-${noteId}`, JSON.stringify(thread)); } catch { /* ignore */ }
}

/** Clears per-note parent-thread localStorage when API returns no threads (avoids stale thread_unorganized for member/shared notes). */
export function clearNoteParentThreadLocalCache(noteId: string) {
  try {
    localStorage.removeItem(`harvous-note-thread-${noteId}`);
    localStorage.removeItem(`harvous-note-thread-data-${noteId}`);
  } catch {
    /* ignore */
  }
}

const NOTE_STALE_TIME = 10_000;

const NOTE_DETAIL_CACHE_PREFIX = 'harvous-note-detail-';
const NOTE_DETAIL_CACHE_INDEX = 'harvous-note-detail-index';
const MAX_CACHED_NOTE_DETAILS = 10;

function getCachedNoteDetail(noteId: string): NoteDetail | undefined {
  try {
    const raw = sessionStorage.getItem(`${NOTE_DETAIL_CACHE_PREFIX}${noteId}`);
    return raw ? JSON.parse(raw) : undefined;
  } catch {
    return undefined;
  }
}

export function clearCachedNoteDetail(noteId: string): void {
  try {
    sessionStorage.removeItem(`${NOTE_DETAIL_CACHE_PREFIX}${noteId}`);
    const raw = sessionStorage.getItem(NOTE_DETAIL_CACHE_INDEX);
    if (raw) {
      const index: string[] = JSON.parse(raw).filter((id: string) => id !== noteId);
      sessionStorage.setItem(NOTE_DETAIL_CACHE_INDEX, JSON.stringify(index));
    }
  } catch {
    /* quota or private browsing */
  }
}

/**
 * Scans localStorage for all note-thread cache entries pointing to `threadId`
 * and removes them. Call on threadDeleted so notes don't back-link to a 404 thread.
 */
export function clearNoteParentThreadCacheByThreadId(threadId: string): void {
  try {
    const keysToRemove: string[] = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (!key?.startsWith('harvous-note-thread-')) continue;
      // Skip the -data- variant here; we'll remove it by derived key below
      if (key.startsWith('harvous-note-thread-data-')) continue;
      const storedThreadId = localStorage.getItem(key);
      if (storedThreadId === threadId) {
        keysToRemove.push(key);
      }
    }
    for (const key of keysToRemove) {
      const noteId = key.slice('harvous-note-thread-'.length);
      localStorage.removeItem(key);
      localStorage.removeItem(`harvous-note-thread-data-${noteId}`);
    }
  } catch {
    /* ignore */
  }
}

export function setCachedNoteDetail(noteId: string, detail: NoteDetail) {
  try {
    sessionStorage.setItem(`${NOTE_DETAIL_CACHE_PREFIX}${noteId}`, JSON.stringify(detail));
    let index: string[] = [];
    try {
      const raw = sessionStorage.getItem(NOTE_DETAIL_CACHE_INDEX);
      index = raw ? JSON.parse(raw) : [];
    } catch {
      index = [];
    }
    index = [noteId, ...index.filter((id) => id !== noteId)];
    while (index.length > MAX_CACHED_NOTE_DETAILS) {
      const evicted = index.pop()!;
      sessionStorage.removeItem(`${NOTE_DETAIL_CACHE_PREFIX}${evicted}`);
    }
    sessionStorage.setItem(NOTE_DETAIL_CACHE_INDEX, JSON.stringify(index));
  } catch {
    /* quota or private browsing */
  }
}

/**
 * Converts a list note (from thread/space notes API) into NoteDetail shape
 * so it can be used as cached data for the note detail query.
 */
export function listNoteToNoteDetail(
  listNote: ListNoteForSeed,
  threadContext: NoteSeedThreadContext
): NoteDetail {
  const threadId = listNote.threadId ?? threadContext.id;
  const thread = {
    id: threadId,
    title: threadContext.title,
    color: threadContext.color,
    backgroundGradient: threadContext.backgroundGradient,
  };
  // Trim a truncated preview back to a clean block boundary so seeding TipTap with it
  // — and later appending the tail — can't split an element mid-way.
  const preview = resolveNoteListPreview(listNote.content, listNote.contentLength);
  return {
    id: listNote.id,
    title: listNote.title ?? null,
    content: listNote.content == null ? null : preview.html,
    noteType: listNote.noteType ?? 'default',
    contentEncrypted: listNote.contentEncrypted ?? false,
    isPublic: false,
    userId: listNote.userId ?? undefined,
    isOwnNote: listNote.isOwnNote,
    spaceId: listNote.spaceId ?? null,
    simpleNoteId: listNote.simpleNoteId ?? undefined,
    createdAt: listNote.createdAt ?? new Date().toISOString(),
    updatedAt: listNote.updatedAt ?? listNote.createdAt ?? new Date().toISOString(),
    threads: [thread],
    tags: [],
    primaryCollection: listNote.primaryCollection ?? null,
    secondaryCollections:
      listNote.secondaryCollections?.length ? [...listNote.secondaryCollections] : [],
    collectionPinned: listNote.collectionPinned ?? false,
    collectionUserOverride: listNote.collectionUserOverride ?? false,
    resourceTitle: listNote.resourceTitle ?? null,
    resourceDescription: listNote.resourceDescription ?? null,
    resourceImage: listNote.resourceImage ?? null,
    version: listNote.version ?? undefined,
    linkedFromNotes: [],
    linkedToNotes: [],
    studyThreads: [],
    __contentIsPreview: true,
    __contentTruncated: preview.truncated,
    __previewLength: preview.previewLength,
  };
}

/**
 * Seeds the note detail cache from a list response so that opening the note
 * shows content immediately. Call when thread/space/dashboard notes are loaded.
 */
export function seedNoteFromList(
  queryClient: QueryClient,
  listNote: ListNoteForSeed,
  threadContext: NoteSeedThreadContext
): void {
  if (!listNote?.id) return;
  const merged = listNoteToNoteDetail(listNote, threadContext);
  const prev =
    queryClient.getQueryData<NoteDetail>(['note', listNote.id]) ?? getCachedNoteDetail(listNote.id);
  if (prev) {
    // List payloads omit tags / study threads / links — never clobber richer detail cache from GET …/details.
    if (prev.tags?.length) merged.tags = prev.tags;
    if (prev.studyThreads?.length) merged.studyThreads = prev.studyThreads;
    if (prev.linkedFromNotes?.length) merged.linkedFromNotes = prev.linkedFromNotes;
    if (prev.linkedToNotes?.length) merged.linkedToNotes = prev.linkedToNotes;
    if (prev.simpleNoteId != null && merged.simpleNoteId == null) merged.simpleNoteId = prev.simpleNoteId;
    // List `content` is a truncated preview (server NOTE_LIST_SELECT). If we already
    // have a fuller body cached (e.g. from GET …/details), keep it rather than
    // downgrading to the preview, and inherit its (non-preview) status.
    if (typeof prev.content === 'string' && prev.content.length >= (merged.content?.length ?? 0)) {
      merged.content = prev.content;
      merged.__contentIsPreview = prev.__contentIsPreview ?? false;
      merged.__contentTruncated = prev.__contentTruncated ?? false;
      merged.__previewLength = prev.__previewLength;
    }
    // List payloads can lag autosave — keep the longer / newer title from detail cache.
    if (typeof prev.title === 'string' && (merged.title?.length ?? 0) < prev.title.length) {
      merged.title = prev.title;
    }
    // Collection fields: detail cache (incl. optimistic patches from useUpdateNote.onSuccess)
    // is the source of truth. Never clobber with stale list-seed values that may lag a
    // just-completed folder update by the list-refetch round trip.
    if ('primaryCollection' in prev) merged.primaryCollection = prev.primaryCollection ?? null;
    if ('secondaryCollections' in prev) {
      merged.secondaryCollections = prev.secondaryCollections ?? [];
    }
    if ('collectionPinned' in prev) merged.collectionPinned = !!prev.collectionPinned;
    if ('collectionUserOverride' in prev) merged.collectionUserOverride = !!prev.collectionUserOverride;
    if (typeof prev.spaceId === 'string' && prev.spaceId.length > 0) merged.spaceId = prev.spaceId;
    // Shared-space membership + co-edit authority are detail-only (list payloads have
    // no equivalent), so a plain merge would wipe them on every list refresh. Callers
    // read `spaces` to decide audience UI and whether a space switch orphans the note;
    // losing it mid-session makes those surfaces blink and mis-decide. Keep `spaces`
    // `undefined` when we've never loaded detail — that's "unknown", not "none".
    if (prev.spaces) merged.spaces = prev.spaces;
    if (typeof prev.coEditEnabled === 'boolean') merged.coEditEnabled = prev.coEditEnabled;
    if (typeof prev.canEdit === 'boolean') merged.canEdit = prev.canEdit;
    if (prev.contributors?.length) merged.contributors = prev.contributors;
    if (typeof prev.authorUserId === 'string' && prev.authorUserId.length > 0) {
      merged.authorUserId = prev.authorUserId;
    }
    if (typeof merged.isOwnNote !== 'boolean' && typeof prev.isOwnNote === 'boolean') {
      merged.isOwnNote = prev.isOwnNote;
    }
  }
  queryClient.setQueryData(['note', listNote.id], merged);
  setCachedNoteDetail(listNote.id, merged);
  // List content is a truncated preview, so mark the note query stale (without an
  // immediate refetch) to ensure opening the note loads the full body via
  // GET /api/notes/:id/details. The preview shows instantly meanwhile, and the
  // sidebar's prefetchQuery will now actually fetch (rather than skip on fresh data).
  queryClient.invalidateQueries({ queryKey: ['note', listNote.id], refetchType: 'none' });
}

/** Parse `note.id` from POST /api/notes/create JSON (handles odd types conservatively). */
export function getNoteIdFromCreateResponse(res: unknown): string | undefined {
  if (!res || typeof res !== 'object') return undefined;
  const note = (res as { note?: unknown }).note;
  if (!note || typeof note !== 'object') return undefined;
  const raw = (note as { id?: unknown }).id;
  if (typeof raw === 'string' && raw.length > 0) return raw;
  if (typeof raw === 'number' && Number.isFinite(raw)) return String(raw);
  return undefined;
}

/** `note` from POST /api/notes/create — extra keys ignored; seed cache for instant editor (prototype / native-like). */
export function seedNoteFromCreateResponse(
  queryClient: QueryClient,
  created: Record<string, unknown> & { id: string },
  requestSpaceId: string,
  metadata?: {
    currentVersion?: number;
    currentVersionId?: string | null;
    contextSpaceId?: string | null;
  },
): void {
  if (!created?.id) return;
  const spaceNorm =
    (typeof created.spaceId === 'string' && created.spaceId.trim()) ||
    (requestSpaceId.startsWith('space_') ? requestSpaceId : `space_${requestSpaceId}`);
  let secondary: string[] | undefined;
  const sc = created.secondaryCollections;
  if (Array.isArray(sc)) {
    secondary = sc.filter((x): x is string => typeof x === 'string');
  }
  const listSeed: ListNoteForSeed = {
    id: created.id,
    title: typeof created.title === 'string' ? created.title : '',
    content: typeof created.content === 'string' ? created.content : '<p></p>',
    noteType: typeof created.noteType === 'string' ? created.noteType : 'default',
    contentEncrypted: created.contentEncrypted === true,
    threadId: 'thread_unorganized',
    spaceId: spaceNorm,
    createdAt: typeof created.createdAt === 'string' ? created.createdAt : undefined,
    updatedAt:
      typeof created.updatedAt === 'string'
        ? created.updatedAt
        : typeof created.createdAt === 'string'
          ? created.createdAt
          : undefined,
    simpleNoteId: typeof created.simpleNoteId === 'number' ? created.simpleNoteId : undefined,
    primaryCollection: typeof created.primaryCollection === 'string' ? created.primaryCollection : null,
    secondaryCollections: secondary,
    resourceTitle: typeof created.resourceTitle === 'string' ? created.resourceTitle : null,
    version: typeof created.version === 'string' ? created.version : undefined,
  };
  const threadContext = {
    id: 'thread_unorganized',
    title: '',
    color: null,
    backgroundGradient: '',
  };
  const versionPatch = {
    ...(typeof metadata?.currentVersion === 'number'
      ? { currentVersion: metadata.currentVersion }
      : {}),
    ...(metadata?.currentVersionId !== undefined
      ? { currentVersionId: metadata.currentVersionId }
      : {}),
  };
  const context = metadata?.contextSpaceId?.trim() || null;
  if (context) {
    queryClient.setQueryData(
      ['note', created.id, context],
      {
        ...listNoteToNoteDetail(listSeed, threadContext),
        ...versionPatch,
        contextSpaceId: context,
      },
    );
    return;
  }
  seedNoteFromList(queryClient, listSeed, threadContext);
  queryClient.setQueryData<NoteDetail>(
    ['note', created.id],
    (cached) => cached ? { ...cached, ...versionPatch } : cached,
  );
}

export function getNoteQueryOptions(noteId: string, contextSpaceId?: string | null) {
  const trimmed = contextSpaceId?.trim() || null;
  // Accept bare URL ids (`1785…`) or `space_*` — API expects the prefixed form.
  const context =
    trimmed == null ? null : trimmed.startsWith('space_') ? trimmed : `space_${trimmed}`;
  const queryKey = context ? (['note', noteId, context] as const) : (['note', noteId] as const);
  return {
    queryKey,
    queryFn: async (): Promise<NoteDetail> => {
      const contextQuery = context ? `?contextSpaceId=${encodeURIComponent(context)}` : '';
      const res = await api.get<NoteDetailResponse>(`/api/notes/${noteId}/details${contextQuery}`);
      const organization = res.context?.organization ?? res.note.organization ?? null;
      const note = {
        ...res.note,
        // Full body from GET …/details — clear list-seed preview markers so the editor
        // can upgrade and release any saves it was holding.
        __contentIsPreview: false,
        __contentTruncated: false,
        currentVersion:
          typeof res.currentVersion === 'number'
            ? res.currentVersion
            : res.currentVersion?.version ?? res.note.currentVersion,
        currentVersionId: res.currentVersionId ?? res.note.currentVersionId,
        contextSpaceId: res.context?.spaceId ?? res.note.contextSpaceId,
        organization,
        ...(organization
          ? {
              primaryCollection: organization.primaryCollection,
              secondaryCollections: organization.secondaryCollections,
              collectionPinned: organization.collectionPinned,
            }
          : {}),
        threads: res.threads ?? [],
        tags: res.tags ?? [],
        linkedFromNotes: Array.isArray(res.linkedFromNotes) ? res.linkedFromNotes : [],
        linkedToNotes: Array.isArray(res.linkedToNotes) ? res.linkedToNotes : [],
        studyThreads: Array.isArray(res.studyThreads) ? res.studyThreads : [],
        spaces: Array.isArray(res.activeSharedAssociations)
          ? res.activeSharedAssociations.map((association) => ({
              id: association.spaceId,
              title: association.spaceTitle,
              coEditEnabled: association.coEditEnabled === true,
              spaceType: association.spaceType,
            }))
          : [],
      } as NoteDetail;
      if (shouldUseNoteOnlyParentThreadCache(context)) {
        const parentThread = note.threads?.[0];
        if (parentThread?.id) {
          try { localStorage.setItem(`harvous-note-thread-${noteId}`, parentThread.id); } catch { /* ignore */ }
          const threadWithCount = parentThread as { count?: number; spaceId?: string | null };
          setCachedNoteParentThread(noteId, {
            id: parentThread.id,
            title: parentThread.title,
            noteCount: threadWithCount.count ?? 0,
            backgroundGradient: parentThread.backgroundGradient ?? 'var(--color-gradient-gray)',
            spaceId: threadWithCount.spaceId ?? null,
          });
        } else {
          clearNoteParentThreadLocalCache(noteId);
        }
      }
      // Shared-context detail is scoped and may expose unioned annotations. Never
      // overwrite the context-free session snapshot used by My Home.
      if (!context) setCachedNoteDetail(noteId, note);
      return note;
    },
    staleTime: NOTE_STALE_TIME,
  };
}

export function useNote(noteId: string, contextSpaceId?: string | null) {
  const context = contextSpaceId?.trim() || null;
  const options = getNoteQueryOptions(noteId, context);
  // Prefer session snapshot for unscoped reads; for shared-context reads, still paint
  // instantly from the unscoped/list seed while the scoped GET …/details runs.
  const cachedDetail = noteId ? getCachedNoteDetail(noteId) : undefined;
  /**
   * Session snapshots from incomplete list seed (or older builds) may omit `simpleNoteId` entirely.
   * Treat that as maximally stale so GET …/details runs; explicit `simpleNoteId: null` (legacy DB) stays normal stale window.
   */
  const initialDataUpdatedAt =
    cachedDetail == null
      ? undefined
      : cachedDetail.__contentIsPreview || context
        ? 0 // preview or shared-context — force GET …/details; still show seed immediately
        : typeof cachedDetail.simpleNoteId === 'number'
          ? Date.now() - 5_000
          : 'simpleNoteId' in cachedDetail
            ? Date.now() - 5_000
            : 0;
  return useQuery({
    ...options,
    enabled: !!noteId,
    initialData: cachedDetail,
    initialDataUpdatedAt,
  });
}
