import { useQuery, QueryClient } from '@tanstack/react-query';
import { api } from '../../lib/api';

/** Thread context when seeding note cache from a list (thread/space page). */
export interface NoteSeedThreadContext {
  id: string;
  title: string;
  color: string | null;
  backgroundGradient: string;
}

/** List note shape from GET /api/threads/:id/notes (or similar). */
export interface ListNoteForSeed {
  id: string;
  title?: string | null;
  content?: string | null;
  contentEncrypted?: boolean;
  noteType?: string;
  threadId?: string;
  spaceId?: string | null;
  simpleNoteId?: number | null;
  createdAt?: string;
  updatedAt?: string;
  resourceTitle?: string | null;
  resourceDescription?: string | null;
  resourceImage?: string | null;
  userId?: string;
  version?: string;
  primaryCollection?: string | null;
  secondaryCollections?: string[];
  collectionPinned?: boolean;
  collectionUserOverride?: boolean;
}

/** Slim linked-note row from GET /api/notes/:id/details (connections strip). */
export interface LinkedNoteRef {
  id: string;
  title?: string | null;
  noteType?: string;
  resourceTitle?: string | null;
  resourceDescription?: string | null;
  resourceImage?: string | null;
}

/** Study thread entry row from GET /api/notes/:id/details (mirrors `StudyThreadEntries` + native StudyThread fields). */
export interface StudyThreadEntryDetail {
  id: string;
  parentNoteId: string;
  spaceId: string | null;
  entryKind: string;
  highlightAccentRaw: string | null;
  sourceSnippet: string | null;
  focusTitle: string | null;
  notesBody: string | null;
  miniNoteBody: string | null;
  linkedNoteId: string | null;
  linkedNoteTitle: string | null;
  anchorLocation: number | null;
  anchorLength: number | null;
  anchorTextSnapshot: string | null;
  scriptureReference: string | null;
  scripturePassageTranslation: string | null;
  scripturePassageExcerpt: string | null;
  isArchived: boolean;
  highlightListEditedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NoteDetail {
  id: string;
  title: string | null;
  content: string | null;
  noteType: string;
  /** 'system' = onboarding seed notes; treat as read-only in the UI. */
  addedBy?: string;
  contentEncrypted: boolean;
  version?: string;
  resourceTitle?: string | null;
  resourceDescription?: string | null;
  resourceImage?: string | null;
  resourceUrl?: string | null;
  simpleNoteId?: number | null;
  isPublic: boolean;
  shareToken?: string | null;
  userId?: string;
  createdAt: string;
  updatedAt: string;
  threads: { id: string; title: string; color: string | null; backgroundGradient?: string }[];
  tags: {
    id: string;
    name: string;
    color?: string | null;
    category?: string | null;
    isSystem?: boolean;
    isAutoGenerated?: boolean | null;
    confidence?: number | null;
  }[];
  spaces?: { id: string; title: string }[];
  linkedFromNoteId?: string | null;
  primaryCollection?: string | null;
  secondaryCollections?: string[];
  collectionPinned?: boolean;
  collectionUserOverride?: boolean;
  collectionLastAutoUpdatedAt?: string | null;
  linkedFromNotes?: LinkedNoteRef[];
  linkedToNotes?: LinkedNoteRef[];
  studyThreads?: StudyThreadEntryDetail[];
  /**
   * Internal: set when `content` was seeded from a list payload (server
   * NOTE_LIST_SELECT), which may be a truncated preview. Signals `useNote` to
   * treat the cached entry as stale so the full body is fetched on open. Cleared
   * once GET /api/notes/:id/details has populated the full detail.
   */
  __contentIsPreview?: boolean;
}

interface NoteDetailResponse {
  success: boolean;
  note: Omit<NoteDetail, 'threads' | 'tags' | 'spaces' | 'linkedFromNotes' | 'linkedToNotes' | 'studyThreads'>;
  threads: NoteDetail['threads'];
  tags?: NoteDetail['tags'];
  linkedFromNotes?: LinkedNoteRef[];
  linkedToNotes?: LinkedNoteRef[];
  studyThreads?: StudyThreadEntryDetail[];
}

export function getCachedNoteParentThreadId(noteId: string): string | null {
  try { return localStorage.getItem(`harvous-note-thread-${noteId}`); } catch { return null; }
}

export interface CachedThread {
  id: string;
  title: string;
  noteCount: number;
  backgroundGradient: string;
  spaceId?: string | null;
}

export function getCachedNoteParentThread(noteId: string): CachedThread | null {
  try {
    const raw = localStorage.getItem(`harvous-note-thread-data-${noteId}`);
    return raw ? JSON.parse(raw) as CachedThread : null;
  } catch { return null; }
}

function setCachedNoteParentThread(noteId: string, thread: CachedThread) {
  try { localStorage.setItem(`harvous-note-thread-data-${noteId}`, JSON.stringify(thread)); } catch { /* ignore */ }
}

/** Clears per-note parent-thread localStorage when API returns no threads (avoids stale thread_unorganized for member/shared notes). */
export function clearNoteParentThreadLocalCache(noteId: string) {
  try {
    localStorage.removeItem(`harvous-note-thread-${noteId}`);
    localStorage.removeItem(`harvous-note-thread-data-${noteId}`);
  } catch {
    /* ignore */
  }
}

const NOTE_STALE_TIME = 10_000;

const NOTE_DETAIL_CACHE_PREFIX = 'harvous-note-detail-';
const NOTE_DETAIL_CACHE_INDEX = 'harvous-note-detail-index';
const MAX_CACHED_NOTE_DETAILS = 10;

function getCachedNoteDetail(noteId: string): NoteDetail | undefined {
  try {
    const raw = sessionStorage.getItem(`${NOTE_DETAIL_CACHE_PREFIX}${noteId}`);
    return raw ? JSON.parse(raw) : undefined;
  } catch {
    return undefined;
  }
}

export function clearCachedNoteDetail(noteId: string): void {
  try {
    sessionStorage.removeItem(`${NOTE_DETAIL_CACHE_PREFIX}${noteId}`);
    const raw = sessionStorage.getItem(NOTE_DETAIL_CACHE_INDEX);
    if (raw) {
      const index: string[] = JSON.parse(raw).filter((id: string) => id !== noteId);
      sessionStorage.setItem(NOTE_DETAIL_CACHE_INDEX, JSON.stringify(index));
    }
  } catch {
    /* quota or private browsing */
  }
}

/**
 * Scans localStorage for all note-thread cache entries pointing to `threadId`
 * and removes them. Call on threadDeleted so notes don't back-link to a 404 thread.
 */
export function clearNoteParentThreadCacheByThreadId(threadId: string): void {
  try {
    const keysToRemove: string[] = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (!key?.startsWith('harvous-note-thread-')) continue;
      // Skip the -data- variant here; we'll remove it by derived key below
      if (key.startsWith('harvous-note-thread-data-')) continue;
      const storedThreadId = localStorage.getItem(key);
      if (storedThreadId === threadId) {
        keysToRemove.push(key);
      }
    }
    for (const key of keysToRemove) {
      const noteId = key.slice('harvous-note-thread-'.length);
      localStorage.removeItem(key);
      localStorage.removeItem(`harvous-note-thread-data-${noteId}`);
    }
  } catch {
    /* ignore */
  }
}

function setCachedNoteDetail(noteId: string, detail: NoteDetail) {
  try {
    sessionStorage.setItem(`${NOTE_DETAIL_CACHE_PREFIX}${noteId}`, JSON.stringify(detail));
    let index: string[] = [];
    try {
      const raw = sessionStorage.getItem(NOTE_DETAIL_CACHE_INDEX);
      index = raw ? JSON.parse(raw) : [];
    } catch {
      index = [];
    }
    index = [noteId, ...index.filter((id) => id !== noteId)];
    while (index.length > MAX_CACHED_NOTE_DETAILS) {
      const evicted = index.pop()!;
      sessionStorage.removeItem(`${NOTE_DETAIL_CACHE_PREFIX}${evicted}`);
    }
    sessionStorage.setItem(NOTE_DETAIL_CACHE_INDEX, JSON.stringify(index));
  } catch {
    /* quota or private browsing */
  }
}

/**
 * Converts a list note (from thread/space notes API) into NoteDetail shape
 * so it can be used as cached data for the note detail query.
 */
export function listNoteToNoteDetail(
  listNote: ListNoteForSeed,
  threadContext: NoteSeedThreadContext
): NoteDetail {
  const threadId = listNote.threadId ?? threadContext.id;
  const thread = {
    id: threadId,
    title: threadContext.title,
    color: threadContext.color,
    backgroundGradient: threadContext.backgroundGradient,
  };
  return {
    id: listNote.id,
    title: listNote.title ?? null,
    content: listNote.content ?? null,
    noteType: listNote.noteType ?? 'default',
    contentEncrypted: listNote.contentEncrypted ?? false,
    isPublic: false,
    userId: listNote.userId ?? undefined,
    simpleNoteId: listNote.simpleNoteId ?? undefined,
    createdAt: listNote.createdAt ?? new Date().toISOString(),
    updatedAt: listNote.updatedAt ?? listNote.createdAt ?? new Date().toISOString(),
    threads: [thread],
    tags: [],
    primaryCollection: listNote.primaryCollection ?? null,
    secondaryCollections:
      listNote.secondaryCollections?.length ? [...listNote.secondaryCollections] : [],
    collectionPinned: listNote.collectionPinned ?? false,
    collectionUserOverride: listNote.collectionUserOverride ?? false,
    resourceTitle: listNote.resourceTitle ?? null,
    resourceDescription: listNote.resourceDescription ?? null,
    resourceImage: listNote.resourceImage ?? null,
    version: listNote.version ?? undefined,
    linkedFromNotes: [],
    linkedToNotes: [],
    studyThreads: [],
    __contentIsPreview: true,
  };
}

/**
 * Seeds the note detail cache from a list response so that opening the note
 * shows content immediately. Call when thread/space/dashboard notes are loaded.
 */
export function seedNoteFromList(
  queryClient: QueryClient,
  listNote: ListNoteForSeed,
  threadContext: NoteSeedThreadContext
): void {
  if (!listNote?.id) return;
  const merged = listNoteToNoteDetail(listNote, threadContext);
  const prev =
    queryClient.getQueryData<NoteDetail>(['note', listNote.id]) ?? getCachedNoteDetail(listNote.id);
  if (prev) {
    // List payloads omit tags / study threads / links — never clobber richer detail cache from GET …/details.
    if (prev.tags?.length) merged.tags = prev.tags;
    if (prev.studyThreads?.length) merged.studyThreads = prev.studyThreads;
    if (prev.linkedFromNotes?.length) merged.linkedFromNotes = prev.linkedFromNotes;
    if (prev.linkedToNotes?.length) merged.linkedToNotes = prev.linkedToNotes;
    if (prev.simpleNoteId != null && merged.simpleNoteId == null) merged.simpleNoteId = prev.simpleNoteId;
    // List `content` is a truncated preview (server NOTE_LIST_SELECT). If we already
    // have a fuller body cached (e.g. from GET …/details), keep it rather than
    // downgrading to the preview, and inherit its (non-preview) status.
    if (typeof prev.content === 'string' && prev.content.length >= (merged.content?.length ?? 0)) {
      merged.content = prev.content;
      merged.__contentIsPreview = prev.__contentIsPreview ?? false;
    }
    // Collection fields: detail cache (incl. optimistic patches from useUpdateNote.onSuccess)
    // is the source of truth. Never clobber with stale list-seed values that may lag a
    // just-completed folder update by the list-refetch round trip.
    if ('primaryCollection' in prev) merged.primaryCollection = prev.primaryCollection ?? null;
    if ('secondaryCollections' in prev) {
      merged.secondaryCollections = prev.secondaryCollections ?? [];
    }
    if ('collectionPinned' in prev) merged.collectionPinned = !!prev.collectionPinned;
    if ('collectionUserOverride' in prev) merged.collectionUserOverride = !!prev.collectionUserOverride;
  }
  queryClient.setQueryData(['note', listNote.id], merged);
  setCachedNoteDetail(listNote.id, merged);
  // List content is a truncated preview, so mark the note query stale (without an
  // immediate refetch) to ensure opening the note loads the full body via
  // GET /api/notes/:id/details. The preview shows instantly meanwhile, and the
  // sidebar's prefetchQuery will now actually fetch (rather than skip on fresh data).
  queryClient.invalidateQueries({ queryKey: ['note', listNote.id], refetchType: 'none' });
}

/** Parse `note.id` from POST /api/notes/create JSON (handles odd types conservatively). */
export function getNoteIdFromCreateResponse(res: unknown): string | undefined {
  if (!res || typeof res !== 'object') return undefined;
  const note = (res as { note?: unknown }).note;
  if (!note || typeof note !== 'object') return undefined;
  const raw = (note as { id?: unknown }).id;
  if (typeof raw === 'string' && raw.length > 0) return raw;
  if (typeof raw === 'number' && Number.isFinite(raw)) return String(raw);
  return undefined;
}

/** `note` from POST /api/notes/create — extra keys ignored; seed cache for instant editor (prototype / native-like). */
export function seedNoteFromCreateResponse(
  queryClient: QueryClient,
  created: Record<string, unknown> & { id: string },
  requestSpaceId: string,
): void {
  if (!created?.id) return;
  const spaceNorm =
    (typeof created.spaceId === 'string' && created.spaceId.trim()) ||
    (requestSpaceId.startsWith('space_') ? requestSpaceId : `space_${requestSpaceId}`);
  let secondary: string[] | undefined;
  const sc = created.secondaryCollections;
  if (Array.isArray(sc)) {
    secondary = sc.filter((x): x is string => typeof x === 'string');
  }
  const listSeed: ListNoteForSeed = {
    id: created.id,
    title: typeof created.title === 'string' ? created.title : '',
    content: typeof created.content === 'string' ? created.content : '<p></p>',
    noteType: typeof created.noteType === 'string' ? created.noteType : 'default',
    contentEncrypted: created.contentEncrypted === true,
    threadId: 'thread_unorganized',
    spaceId: spaceNorm,
    createdAt: typeof created.createdAt === 'string' ? created.createdAt : undefined,
    updatedAt:
      typeof created.updatedAt === 'string'
        ? created.updatedAt
        : typeof created.createdAt === 'string'
          ? created.createdAt
          : undefined,
    simpleNoteId: typeof created.simpleNoteId === 'number' ? created.simpleNoteId : undefined,
    primaryCollection: typeof created.primaryCollection === 'string' ? created.primaryCollection : null,
    secondaryCollections: secondary,
    resourceTitle: typeof created.resourceTitle === 'string' ? created.resourceTitle : null,
    version: typeof created.version === 'string' ? created.version : undefined,
  };
  seedNoteFromList(queryClient, listSeed, {
    id: 'thread_unorganized',
    title: '',
    color: null,
    backgroundGradient: '',
  });
}

export function getNoteQueryOptions(noteId: string) {
  return {
    queryKey: ['note', noteId] as const,
    queryFn: async (): Promise<NoteDetail> => {
      const res = await api.get<NoteDetailResponse>(`/api/notes/${noteId}/details`);
      const note = {
        ...res.note,
        threads: res.threads ?? [],
        tags: res.tags ?? [],
        linkedFromNotes: Array.isArray(res.linkedFromNotes) ? res.linkedFromNotes : [],
        linkedToNotes: Array.isArray(res.linkedToNotes) ? res.linkedToNotes : [],
        studyThreads: Array.isArray(res.studyThreads) ? res.studyThreads : [],
      } as NoteDetail;
      const parentThread = note.threads?.[0];
      if (parentThread?.id) {
        try { localStorage.setItem(`harvous-note-thread-${noteId}`, parentThread.id); } catch { /* ignore */ }
        const threadWithCount = parentThread as { count?: number; spaceId?: string | null };
        setCachedNoteParentThread(noteId, {
          id: parentThread.id,
          title: parentThread.title,
          noteCount: threadWithCount.count ?? 0,
          backgroundGradient: parentThread.backgroundGradient ?? 'var(--color-gradient-gray)',
          spaceId: threadWithCount.spaceId ?? null,
        });
      } else {
        clearNoteParentThreadLocalCache(noteId);
      }
      setCachedNoteDetail(noteId, note);
      return note;
    },
    staleTime: NOTE_STALE_TIME,
  };
}

export function useNote(noteId: string) {
  const options = getNoteQueryOptions(noteId);
  const cachedDetail = noteId ? getCachedNoteDetail(noteId) : undefined;
  /**
   * Session snapshots from incomplete list seed (or older builds) may omit `simpleNoteId` entirely.
   * Treat that as maximally stale so GET …/details runs; explicit `simpleNoteId: null` (legacy DB) stays normal stale window.
   */
  const initialDataUpdatedAt =
    cachedDetail == null
      ? undefined
      : cachedDetail.__contentIsPreview
        ? 0 // content is a truncated list preview — force GET …/details for the full body
        : typeof cachedDetail.simpleNoteId === 'number'
          ? Date.now() - 5_000
          : 'simpleNoteId' in cachedDetail
            ? Date.now() - 5_000
            : 0;
  return useQuery({
    ...options,
    enabled: !!noteId,
    initialData: cachedDetail,
    initialDataUpdatedAt,
  });
}
