export const prerender = false;

import type { APIRoute } from 'astro';
import { db, Spaces, Threads, Notes, NoteThreads, Tags, NoteTags, UserMetadata, eq } from 'astro:db';
import { getCurrentSeason } from '@/utils/season-helpers';
import { handleAPIError } from '@/utils/error-handling';
import { unauthorizedResponse, serverErrorResponse } from '@/utils/api-responses';

/**
 * Bootstrap endpoint for offline-first sync
 * Returns all user data needed to populate local IndexedDB on first load
 */
export const GET: APIRoute = async ({ request, locals }) => {
  try {
    const { userId } = locals.auth();
    
    if (!userId) {
      return unauthorizedResponse();
    }

    // Fetch all user data in parallel for efficiency
    const [
      spaces,
      threads,
      notes,
      noteThreads,
      tags,
      noteTags,
      userMetadata
    ] = await Promise.all([
      // Spaces
      db.select({
        id: Spaces.id,
        title: Spaces.title,
        description: Spaces.description,
        color: Spaces.color,
        backgroundGradient: Spaces.backgroundGradient,
        isPublic: Spaces.isPublic,
        isActive: Spaces.isActive,
        order: Spaces.order,
        createdAt: Spaces.createdAt,
        updatedAt: Spaces.updatedAt,
      })
      .from(Spaces)
      .where(eq(Spaces.userId, userId))
      .all(),

      // Threads
      db.select({
        id: Threads.id,
        title: Threads.title,
        subtitle: Threads.subtitle,
        spaceId: Threads.spaceId,
        color: Threads.color,
        isPublic: Threads.isPublic,
        isPinned: Threads.isPinned,
        order: Threads.order,
        lastVisited: Threads.lastVisited,
        createdAt: Threads.createdAt,
        updatedAt: Threads.updatedAt,
      })
      .from(Threads)
      .where(eq(Threads.userId, userId))
      .all(),

      // Notes (limit to reasonable amount for initial bootstrap - can be paginated later)
      db.select({
        id: Notes.id,
        title: Notes.title,
        content: Notes.content,
        threadId: Notes.threadId,
        spaceId: Notes.spaceId,
        simpleNoteId: Notes.simpleNoteId,
        noteType: Notes.noteType,
        addedBy: Notes.addedBy,
        isPublic: Notes.isPublic,
        isFeatured: Notes.isFeatured,
        order: Notes.order,
        lastVisited: Notes.lastVisited,
        createdAt: Notes.createdAt,
        updatedAt: Notes.updatedAt,
        contentEncrypted: Notes.contentEncrypted,
      })
      .from(Notes)
      .where(eq(Notes.userId, userId))
      .limit(1000) // Reasonable limit for initial bootstrap
      .all(),

      // NoteThreads junction table
      db.select({
        id: NoteThreads.id,
        noteId: NoteThreads.noteId,
        threadId: NoteThreads.threadId,
        createdAt: NoteThreads.createdAt,
      })
      .from(NoteThreads)
      .innerJoin(Notes, eq(Notes.id, NoteThreads.noteId))
      .where(eq(Notes.userId, userId))
      .all(),

      // Tags
      db.select({
        id: Tags.id,
        name: Tags.name,
        color: Tags.color,
        category: Tags.category,
        isSystem: Tags.isSystem,
        createdAt: Tags.createdAt,
        updatedAt: Tags.updatedAt,
      })
      .from(Tags)
      .where(eq(Tags.userId, userId))
      .all(),

      // NoteTags junction table
      db.select({
        id: NoteTags.id,
        noteId: NoteTags.noteId,
        tagId: NoteTags.tagId,
        isAutoGenerated: NoteTags.isAutoGenerated,
        confidence: NoteTags.confidence,
        createdAt: NoteTags.createdAt,
      })
      .from(NoteTags)
      .innerJoin(Notes, eq(Notes.id, NoteTags.noteId))
      .where(eq(Notes.userId, userId))
      .all(),

      // UserMetadata (lockPinHash used only to derive hasLockPinSet; never sent to client)
      db.select({
        id: UserMetadata.id,
        userId: UserMetadata.userId,
        highestSimpleNoteId: UserMetadata.highestSimpleNoteId,
        userColor: UserMetadata.userColor,
        firstName: UserMetadata.firstName,
        lastName: UserMetadata.lastName,
        email: UserMetadata.email,
        profileImageUrl: UserMetadata.profileImageUrl,
        clerkDataUpdatedAt: UserMetadata.clerkDataUpdatedAt,
        churchName: UserMetadata.churchName,
        churchCity: UserMetadata.churchCity,
        churchState: UserMetadata.churchState,
        churchCountry: UserMetadata.churchCountry,
        currentSeason: UserMetadata.currentSeason,
        lastMonthlyVisit: UserMetadata.lastMonthlyVisit,
        churchAddedAt: UserMetadata.churchAddedAt,
        createdAt: UserMetadata.createdAt,
        updatedAt: UserMetadata.updatedAt,
        lockPinHash: UserMetadata.lockPinHash,
      })
      .from(UserMetadata)
      .where(eq(UserMetadata.userId, userId))
      .get(),
    ]);

    // Calculate reserved ID range for offline note creation
    // Reserve next 200 IDs for offline use
    const highestSimpleNoteId = userMetadata?.highestSimpleNoteId || 0;
    const reservedRange = {
      start: highestSimpleNoteId + 1,
      end: highestSimpleNoteId + 200,
    };

    // Backfill currentSeason so users never have null (fixes existing rows)
    let userMetaForResponse = userMetadata;
    if (userMetadata?.currentSeason == null) {
      const season = getCurrentSeason();
      await db.update(UserMetadata).set({ currentSeason: season, updatedAt: new Date() }).where(eq(UserMetadata.userId, userId));
      userMetaForResponse = { ...userMetadata, currentSeason: season };
    }

    // Format response with timestamps as ISO strings for JSON serialization
    const bootstrapData = {
      timestamp: new Date().toISOString(),
      cursor: `bootstrap_${Date.now()}`, // Cursor for incremental sync
      spaces: spaces.map(space => ({
        ...space,
        createdAt: space.createdAt.toISOString(),
        updatedAt: space.updatedAt?.toISOString() || null,
      })),
      threads: threads.map(thread => ({
        ...thread,
        lastVisited: thread.lastVisited?.toISOString() || null,
        createdAt: thread.createdAt.toISOString(),
        updatedAt: thread.updatedAt?.toISOString() || null,
      })),
      notes: notes.map(note => ({
        ...note,
        lastVisited: note.lastVisited?.toISOString() || null,
        createdAt: note.createdAt.toISOString(),
        updatedAt: note.updatedAt?.toISOString() || null,
      })),
      noteThreads: noteThreads.map(nt => ({
        ...nt,
        createdAt: nt.createdAt.toISOString(),
      })),
      tags: tags.map(tag => ({
        ...tag,
        createdAt: tag.createdAt.toISOString(),
        updatedAt: tag.updatedAt?.toISOString() || null,
      })),
      noteTags: noteTags.map(nt => ({
        ...nt,
        createdAt: nt.createdAt.toISOString(),
      })),
      userMetadata: userMetaForResponse ? (() => {
        const { lockPinHash, ...rest } = userMetaForResponse;
        return {
          ...rest,
          hasLockPinSet: !!lockPinHash,
          highestSimpleNoteId: rest.highestSimpleNoteId,
          reservedSimpleNoteIdRange: reservedRange,
          clerkDataUpdatedAt: rest.clerkDataUpdatedAt?.toISOString() || null,
          lastMonthlyVisit: rest.lastMonthlyVisit?.toISOString() || null,
          churchAddedAt: rest.churchAddedAt?.toISOString() || null,
          createdAt: rest.createdAt.toISOString(),
          updatedAt: rest.updatedAt?.toISOString() || null,
        };
      })() : null,
    };

    return new Response(JSON.stringify(bootstrapData), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'private, no-cache', // Don't cache bootstrap data
      }
    });

  } catch (error) {
    const standardError = handleAPIError(error, {
      endpoint: '/api/sync/bootstrap',
      action: 'bootstrap_sync'
    });
    return serverErrorResponse(standardError.message, standardError.code);
  }
};

