import type { APIRoute } from 'astro';
import { db, Spaces, Threads, Notes, NoteThreads, Tags, NoteTags, UserMetadata, eq, gt, and } from 'astro:db';
import { handleAPIError } from '@/utils/error-handling';
import { unauthorizedResponse, serverErrorResponse, errorResponse } from '@/utils/api-responses';

/**
 * Incremental sync endpoint
 * Returns changes since a given cursor/timestamp
 */
export const GET: APIRoute = async ({ request, locals }) => {
  try {
    const { userId } = locals.auth();
    
    if (!userId) {
      return unauthorizedResponse();
    }

    const url = new URL(request.url);
    const sinceParam = url.searchParams.get('since');
    
    if (!sinceParam) {
      return errorResponse('since parameter is required', 'MISSING_PARAMETER', 400);
    }

    // Parse cursor - format: timestamp_<timestamp> or bootstrap_<timestamp>
    let sinceTimestamp: number;
    if (sinceParam.startsWith('bootstrap_') || sinceParam.startsWith('timestamp_')) {
      sinceTimestamp = parseInt(sinceParam.split('_')[1], 10);
    } else {
      // Try parsing as direct timestamp
      sinceTimestamp = parseInt(sinceParam, 10);
      if (isNaN(sinceTimestamp)) {
        return errorResponse('Invalid since parameter format', 'INVALID_PARAMETER', 400);
      }
    }

    const sinceDate = new Date(sinceTimestamp);

    // Fetch changes since the timestamp
    // Note: We check updatedAt OR createdAt for new items
    const [
      changedSpaces,
      changedThreads,
      changedNotes,
      changedNoteThreads,
      changedTags,
      changedNoteTags,
      changedUserMetadata
    ] = await Promise.all([
      // Spaces changed since timestamp
      db.select({
        id: Spaces.id,
        title: Spaces.title,
        description: Spaces.description,
        color: Spaces.color,
        backgroundGradient: Spaces.backgroundGradient,
        isPublic: Spaces.isPublic,
        isActive: Spaces.isActive,
        order: Spaces.order,
        createdAt: Spaces.createdAt,
        updatedAt: Spaces.updatedAt,
      })
      .from(Spaces)
      .where(and(
        eq(Spaces.userId, userId),
        gt(Spaces.updatedAt || Spaces.createdAt, sinceDate)
      ))
      .all(),

      // Threads changed since timestamp
      db.select({
        id: Threads.id,
        title: Threads.title,
        subtitle: Threads.subtitle,
        spaceId: Threads.spaceId,
        color: Threads.color,
        isPublic: Threads.isPublic,
        isPinned: Threads.isPinned,
        order: Threads.order,
        lastVisited: Threads.lastVisited,
        createdAt: Threads.createdAt,
        updatedAt: Threads.updatedAt,
      })
      .from(Threads)
      .where(and(
        eq(Threads.userId, userId),
        gt(Threads.updatedAt || Threads.createdAt, sinceDate)
      ))
      .all(),

      // Notes changed since timestamp
      db.select({
        id: Notes.id,
        title: Notes.title,
        content: Notes.content,
        threadId: Notes.threadId,
        spaceId: Notes.spaceId,
        simpleNoteId: Notes.simpleNoteId,
        noteType: Notes.noteType,
        addedBy: Notes.addedBy,
        isPublic: Notes.isPublic,
        isFeatured: Notes.isFeatured,
        order: Notes.order,
        lastVisited: Notes.lastVisited,
        createdAt: Notes.createdAt,
        updatedAt: Notes.updatedAt,
      })
      .from(Notes)
      .where(and(
        eq(Notes.userId, userId),
        gt(Notes.updatedAt || Notes.createdAt, sinceDate)
      ))
      .all(),

      // NoteThreads changed since timestamp
      db.select({
        id: NoteThreads.id,
        noteId: NoteThreads.noteId,
        threadId: NoteThreads.threadId,
        createdAt: NoteThreads.createdAt,
      })
      .from(NoteThreads)
      .innerJoin(Notes, eq(Notes.id, NoteThreads.noteId))
      .where(and(
        eq(Notes.userId, userId),
        gt(NoteThreads.createdAt, sinceDate)
      ))
      .all(),

      // Tags changed since timestamp
      db.select({
        id: Tags.id,
        name: Tags.name,
        color: Tags.color,
        category: Tags.category,
        isSystem: Tags.isSystem,
        createdAt: Tags.createdAt,
        updatedAt: Tags.updatedAt,
      })
      .from(Tags)
      .where(and(
        eq(Tags.userId, userId),
        gt(Tags.updatedAt || Tags.createdAt, sinceDate)
      ))
      .all(),

      // NoteTags changed since timestamp
      db.select({
        id: NoteTags.id,
        noteId: NoteTags.noteId,
        tagId: NoteTags.tagId,
        isAutoGenerated: NoteTags.isAutoGenerated,
        confidence: NoteTags.confidence,
        createdAt: NoteTags.createdAt,
      })
      .from(NoteTags)
      .innerJoin(Notes, eq(Notes.id, NoteTags.noteId))
      .where(and(
        eq(Notes.userId, userId),
        gt(NoteTags.createdAt, sinceDate)
      ))
      .all(),

      // UserMetadata changed since timestamp
      db.select({
        id: UserMetadata.id,
        userId: UserMetadata.userId,
        highestSimpleNoteId: UserMetadata.highestSimpleNoteId,
        userColor: UserMetadata.userColor,
        firstName: UserMetadata.firstName,
        lastName: UserMetadata.lastName,
        email: UserMetadata.email,
        profileImageUrl: UserMetadata.profileImageUrl,
        clerkDataUpdatedAt: UserMetadata.clerkDataUpdatedAt,
        churchName: UserMetadata.churchName,
        churchCity: UserMetadata.churchCity,
        churchState: UserMetadata.churchState,
        churchCountry: UserMetadata.churchCountry,
        currentSeason: UserMetadata.currentSeason,
        lastMonthlyVisit: UserMetadata.lastMonthlyVisit,
        churchAddedAt: UserMetadata.churchAddedAt,
        createdAt: UserMetadata.createdAt,
        updatedAt: UserMetadata.updatedAt,
      })
      .from(UserMetadata)
      .where(and(
        eq(UserMetadata.userId, userId),
        gt(UserMetadata.updatedAt || UserMetadata.createdAt, sinceDate)
      ))
      .get(),
    ]);

    // Format response
    const changes = {
      timestamp: new Date().toISOString(),
      cursor: `timestamp_${Date.now()}`,
      hasChanges: changedSpaces.length > 0 || 
                   changedThreads.length > 0 || 
                   changedNotes.length > 0 || 
                   changedNoteThreads.length > 0 ||
                   changedTags.length > 0 ||
                   changedNoteTags.length > 0 ||
                   changedUserMetadata !== null,
      spaces: changedSpaces.map(space => ({
        ...space,
        createdAt: space.createdAt.toISOString(),
        updatedAt: space.updatedAt?.toISOString() || null,
      })),
      threads: changedThreads.map(thread => ({
        ...thread,
        lastVisited: thread.lastVisited?.toISOString() || null,
        createdAt: thread.createdAt.toISOString(),
        updatedAt: thread.updatedAt?.toISOString() || null,
      })),
      notes: changedNotes.map(note => ({
        ...note,
        lastVisited: note.lastVisited?.toISOString() || null,
        createdAt: note.createdAt.toISOString(),
        updatedAt: note.updatedAt?.toISOString() || null,
      })),
      noteThreads: changedNoteThreads.map(nt => ({
        ...nt,
        createdAt: nt.createdAt.toISOString(),
      })),
      tags: changedTags.map(tag => ({
        ...tag,
        createdAt: tag.createdAt.toISOString(),
        updatedAt: tag.updatedAt?.toISOString() || null,
      })),
      noteTags: changedNoteTags.map(nt => ({
        ...nt,
        createdAt: nt.createdAt.toISOString(),
      })),
      userMetadata: changedUserMetadata ? {
        ...changedUserMetadata,
        clerkDataUpdatedAt: changedUserMetadata.clerkDataUpdatedAt?.toISOString() || null,
        lastMonthlyVisit: changedUserMetadata.lastMonthlyVisit?.toISOString() || null,
        churchAddedAt: changedUserMetadata.churchAddedAt?.toISOString() || null,
        createdAt: changedUserMetadata.createdAt.toISOString(),
        updatedAt: changedUserMetadata.updatedAt?.toISOString() || null,
      } : null,
    };

    return new Response(JSON.stringify(changes), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'private, no-cache',
      }
    });

  } catch (error) {
    const standardError = handleAPIError(error, {
      endpoint: '/api/sync/changes',
      action: 'incremental_sync'
    });
    return serverErrorResponse(standardError.message, standardError.code);
  }
};

