/**
 * Client-side auto-tag suggestions — aligns with `server/utils/auto-tag-generator.ts`
 * and native `BibleStudyTagSuggester` using the shared keyword corpus.
 */

import { conceptOverlapsAny } from '@/utils/bible-study-concept-overlaps';
import { shouldSuppressJesusAutoTag } from '@/utils/christ-keyword-context';
import { stripHtml } from '@/utils/html-stripper';
import { findKeywordsInTextWithPriority } from '@/utils/bible-study-keywords';
import { detectPersonTags } from '@/utils/person-tag-detector';
import { subjectTagCandidatesFromText } from '@/utils/subject-tag-candidates';

const DEFAULT_CONFIDENCE_THRESHOLD = 0.7;
const MAX_TAGS = 12;

export interface SuggestAutoTagsOptions {
  confidenceThreshold?: number;
  /** Primary + secondary folder labels — excluded from tag suggestions (cascade hierarchy). */
  excludeFolderLabels?: string[];
  /** Normalized auto-tag names the user dismissed — excluded from suggestions. */
  excludeTagNames?: string[];
}

export interface SuggestedAutoTag {
  name: string;
  category: string;
  confidence: number;
  /** When set, tag came from subject vocabulary (informal prose → canonical subject). */
  source?: 'keyword' | 'subject' | 'person';
  /** Informal phrase that matched (subject tags only). */
  matchedPhrase?: string;
}

/** Top keyword-based tag names from title + HTML body (no DB / existing-tag resolution). */
export function suggestAutoTagsFromNote(
  title: string,
  bodyHtml: string,
  options?: SuggestAutoTagsOptions | number,
): SuggestedAutoTag[] {
  const opts: SuggestAutoTagsOptions =
    typeof options === 'number' ? { confidenceThreshold: options } : (options ?? {});
  const confidenceThreshold = opts.confidenceThreshold ?? DEFAULT_CONFIDENCE_THRESHOLD;
  const excludeFolderLabels = opts.excludeFolderLabels ?? [];
  const excludeTagNames = opts.excludeTagNames ?? [];
  const isExcluded = (name: string) =>
    conceptOverlapsAny(name, excludeFolderLabels) || conceptOverlapsAny(name, excludeTagNames);

  const cleanTitle = (title || '').trim();
  const cleanContent = stripHtml(bodyHtml || '', { preserveSpacing: true }).trim();
  const fullText = `${cleanTitle} ${cleanContent}`.trim();
  if (!fullText) return [];

  let foundKeywords: Array<{ keyword: { name: string; category: string }; confidence: number }> = [];
  try {
    foundKeywords = findKeywordsInTextWithPriority(fullText, cleanTitle, cleanContent);
  } catch {
    foundKeywords = [];
  }

  const suggestions: SuggestedAutoTag[] = [];
  const fullTextLower = fullText.toLowerCase();
  const titleLower = cleanTitle.toLowerCase();
  const hasLiteralJesus = /\bjesus\b/i.test(cleanTitle) || /\bjesus\b/i.test(cleanContent);

  for (const { keyword, confidence } of foundKeywords) {
    if (keyword.name.toLowerCase() === 'god') continue;
    if (
      shouldSuppressJesusAutoTag(keyword.name, confidence, fullTextLower, titleLower, {
        synonymOnly: !hasLiteralJesus,
      })
    ) {
      continue;
    }
    if (confidence < confidenceThreshold) continue;
    if (isExcluded(keyword.name)) continue;
    if (suggestions.some((existing) => conceptOverlapsAny(keyword.name, [existing.name]))) continue;
    suggestions.push({ name: keyword.name, category: keyword.category, confidence, source: 'keyword' });
  }

  suggestions.sort((a, b) => b.confidence - a.confidence);
  const bibleStudyCategories = ['spiritual', 'biblical', 'character', 'book', 'theme'];
  const enhanced = suggestions.map((suggestion) => {
    if (bibleStudyCategories.includes(suggestion.category)) {
      return { ...suggestion, confidence: Math.min(1, suggestion.confidence + 0.05) };
    }
    return suggestion;
  });
  enhanced.sort((a, b) => b.confidence - a.confidence);

  const subjectCandidates = subjectTagCandidatesFromText(cleanTitle, cleanContent, {
    excludeFolderLabels,
    excludeTagNames,
    existingTagNames: enhanced.map((s) => s.name),
    confidenceThreshold,
  });
  for (const sc of subjectCandidates) {
    if (enhanced.some((s) => conceptOverlapsAny(sc.name, [s.name]))) continue;
    enhanced.push({
      name: sc.name,
      category: sc.category,
      confidence: sc.confidence,
      source: 'subject',
      matchedPhrase: sc.matchedPhrase,
    });
  }
  enhanced.sort((a, b) => b.confidence - a.confidence);

  for (const personTag of detectPersonTags(fullText)) {
    const key = personTag.toLowerCase();
    if (enhanced.some((s) => s.name.toLowerCase() === key)) continue;
    if (isExcluded(personTag)) continue;
    enhanced.push({ name: personTag, category: 'character', confidence: 0.85, source: 'person' });
  }
  enhanced.sort((a, b) => b.confidence - a.confidence);

  return enhanced.slice(0, MAX_TAGS);
}

export type NoteTagPreview = {
  id: string;
  name: string;
  color?: string | null;
  category?: string | null;
  isSystem?: boolean;
  isAutoGenerated?: boolean | null;
  confidence?: number | null;
  source?: 'keyword' | 'subject' | 'person';
  matchedPhrase?: string;
};

/** Map suggested tags to note-detail tag rows with stable preview ids until server ids arrive. */
export function suggestedAutoTagsToNoteTags(suggestions: SuggestedAutoTag[]): NoteTagPreview[] {
  return suggestions.map((s) => ({
    id: `preview:${s.name.toLowerCase()}`,
    name: s.name,
    category: s.category,
    isAutoGenerated: true,
    confidence: s.confidence,
    source: s.source,
    matchedPhrase: s.matchedPhrase,
  }));
}
