/**
 * Client-side auto-tag suggestions — aligns with `server/utils/auto-tag-generator.ts`
 * and native `BibleStudyTagSuggester` using the shared keyword corpus.
 */

import { stripHtml } from '@/utils/html-stripper';
import { findKeywordsInTextWithPriority } from '@/utils/bible-study-keywords';
import { detectPersonTags } from '@/utils/person-tag-detector';

const DEFAULT_CONFIDENCE_THRESHOLD = 0.7;
const MAX_TAGS = 12;

function isTagOverlapping(newTag: string, existingTag: string): boolean {
  const newLower = newTag.toLowerCase();
  const existingLower = existingTag.toLowerCase();
  if (newLower === existingLower) return true;
  if (newLower.includes(existingLower) || existingLower.includes(newLower)) return true;
  const overlappingPairs = [
    ['goodness', 'righteousness'],
    ['grace', 'mercy'],
    ['love', 'mercy'],
    ['faith', 'belief'],
    ['hope', 'faith'],
    ['peace', 'joy'],
    ['kingdom of god', 'heaven'],
    ['resurrection', 'eternal life'],
    ['eternal life', 'everlasting life'],
    ['holy spirit', 'spirit'],
    ['jesus', 'christ'],
    ['jesus', 'lord'],
    ['god', 'father'],
    ['god', 'lord'],
  ];
  for (const [tag1, tag2] of overlappingPairs) {
    if ((newLower === tag1 && existingLower === tag2) || (newLower === tag2 && existingLower === tag1)) {
      return true;
    }
  }
  return false;
}

export interface SuggestedAutoTag {
  name: string;
  category: string;
  confidence: number;
}

/** Top keyword-based tag names from title + HTML body (no DB / existing-tag resolution). */
export function suggestAutoTagsFromNote(
  title: string,
  bodyHtml: string,
  confidenceThreshold: number = DEFAULT_CONFIDENCE_THRESHOLD,
): SuggestedAutoTag[] {
  const cleanTitle = (title || '').trim();
  const cleanContent = stripHtml(bodyHtml || '', { preserveSpacing: true }).trim();
  const fullText = `${cleanTitle} ${cleanContent}`.trim();
  if (!fullText) return [];

  let foundKeywords: Array<{ keyword: { name: string; category: string }; confidence: number }> = [];
  try {
    foundKeywords = findKeywordsInTextWithPriority(fullText, cleanTitle, cleanContent);
  } catch {
    foundKeywords = [];
  }

  const suggestions: SuggestedAutoTag[] = [];
  for (const { keyword, confidence } of foundKeywords) {
    if (keyword.name.toLowerCase() === 'god') continue;
    if (confidence < confidenceThreshold) continue;
    if (suggestions.some((existing) => isTagOverlapping(keyword.name, existing.name))) continue;
    suggestions.push({ name: keyword.name, category: keyword.category, confidence });
  }

  suggestions.sort((a, b) => b.confidence - a.confidence);
  const bibleStudyCategories = ['spiritual', 'biblical', 'character', 'book', 'theme'];
  const enhanced = suggestions.map((suggestion) => {
    if (bibleStudyCategories.includes(suggestion.category)) {
      return { ...suggestion, confidence: Math.min(1, suggestion.confidence + 0.05) };
    }
    return suggestion;
  });
  enhanced.sort((a, b) => b.confidence - a.confidence);

  for (const personTag of detectPersonTags(fullText)) {
    const key = personTag.toLowerCase();
    if (enhanced.some((s) => s.name.toLowerCase() === key)) continue;
    enhanced.push({ name: personTag, category: 'character', confidence: 0.85 });
  }
  enhanced.sort((a, b) => b.confidence - a.confidence);

  return enhanced.slice(0, MAX_TAGS);
}

export type NoteTagPreview = {
  id: string;
  name: string;
  color?: string | null;
  category?: string | null;
  isSystem?: boolean;
  isAutoGenerated?: boolean | null;
  confidence?: number | null;
};

/** Map suggested tags to note-detail tag rows with stable preview ids until server ids arrive. */
export function suggestedAutoTagsToNoteTags(suggestions: SuggestedAutoTag[]): NoteTagPreview[] {
  return suggestions.map((s) => ({
    id: `preview:${s.name.toLowerCase()}`,
    name: s.name,
    category: s.category,
    isAutoGenerated: true,
    confidence: s.confidence,
  }));
}
