import Dexie, { Table } from 'dexie';

// Sync status for offline entities
export type SyncStatus = 'synced' | 'pending' | 'conflict' | 'deleted';

// Base interface for all offline entities
interface BaseOfflineEntity {
  id: string;
  userId: string; // Clerk user ID for partitioning
  syncStatus: SyncStatus;
  lastModified: number; // Timestamp for conflict resolution
  serverVersion?: number; // Server-side version/timestamp for conflict detection
  createdAt: Date;
  updatedAt: Date | null;
}

// Offline Space entity
export interface OfflineSpace extends BaseOfflineEntity {
  title: string;
  description: string | null;
  color: string | null;
  backgroundGradient: string | null;
  isPublic: boolean;
  isActive: boolean;
  order: number;
}

// Offline Thread entity
export interface OfflineThread extends BaseOfflineEntity {
  title: string;
  subtitle: string | null;
  spaceId: string | null;
  color: string | null;
  isPublic: boolean;
  isPinned: boolean;
  order: number;
  lastVisited: Date | null;
}

// Offline Note entity
export interface OfflineNote extends BaseOfflineEntity {
  title: string | null;
  content: string;
  threadId: string; // Legacy field (always 'thread_unorganized')
  spaceId: string | null;
  simpleNoteId: number | null;
  noteType: 'default' | 'scripture' | 'resource';
  addedBy: string;
  isPublic: boolean;
  isFeatured: boolean;
  order: number;
  lastVisited: Date | null;
}

// Offline NoteThread junction entity
export interface OfflineNoteThread extends BaseOfflineEntity {
  noteId: string;
  threadId: string;
}

// Offline Tag entity
export interface OfflineTag extends BaseOfflineEntity {
  name: string;
  color: string | null;
  category: string | null;
  isSystem: boolean;
}

// Offline NoteTag junction entity
export interface OfflineNoteTag extends BaseOfflineEntity {
  noteId: string;
  tagId: string;
  isAutoGenerated: boolean;
  confidence: number | null;
}

// Offline UserMetadata entity
export interface OfflineUserMetadata extends BaseOfflineEntity {
  highestSimpleNoteId: number;
  reservedSimpleNoteIdRange: { start: number; end: number } | null; // Reserved range for offline allocation
  usedReservedIds: number[]; // Track which IDs from reserved range have been used
  userColor: string;
  firstName: string | null;
  lastName: string | null;
  email: string | null;
  profileImageUrl: string | null;
  clerkDataUpdatedAt: Date | null;
  churchName: string | null;
  churchCity: string | null;
  churchState: string | null;
  churchCountry: string | null;
  currentSeason: string | null;
  lastMonthlyVisit: Date | null;
  churchAddedAt: Date | null;
}

// Sync operation for mutation queue
export interface SyncOperation {
  id?: number; // Auto-increment primary key
  userId: string; // Clerk user ID
  operation: 'create' | 'update' | 'delete';
  entityType: 'space' | 'thread' | 'note' | 'noteThread' | 'tag' | 'noteTag';
  entityId: string; // Local ID (may be replaced with server ID after sync)
  data: any; // Full entity data or partial update
  timestamp: number; // When the operation was queued
  retryCount: number; // Number of retry attempts
  lastError?: string; // Last error message if sync failed
  serverId?: string; // Server-assigned ID after successful sync
}

// Sync state for tracking sync progress
export interface SyncState {
  userId: string; // Clerk user ID (primary key)
  lastSyncCursor: string | null; // Cursor for incremental sync
  lastSyncTimestamp: number | null; // Last successful sync timestamp
  lastBootstrapTimestamp: number | null; // When bootstrap was last completed
  isSyncing: boolean; // Whether sync is currently in progress
  syncError: string | null; // Last sync error
}

// Offline database class
class OfflineDatabase extends Dexie {
  spaces!: Table<OfflineSpace>;
  threads!: Table<OfflineThread>;
  notes!: Table<OfflineNote>;
  noteThreads!: Table<OfflineNoteThread>;
  tags!: Table<OfflineTag>;
  noteTags!: Table<OfflineNoteTag>;
  userMetadata!: Table<OfflineUserMetadata>;
  syncQueue!: Table<SyncOperation>;
  syncState!: Table<SyncState>;

  constructor() {
    super('HarvousOfflineDB');
    
    // Define schema with indexes for efficient queries
    this.version(1).stores({
      // Spaces: indexed by userId, spaceId, syncStatus, lastModified
      spaces: 'id, userId, syncStatus, lastModified, [userId+syncStatus]',
      
      // Threads: indexed by userId, threadId, spaceId, syncStatus, lastModified
      threads: 'id, userId, spaceId, syncStatus, lastModified, [userId+spaceId], [userId+syncStatus]',
      
      // Notes: indexed by userId, noteId, threadId, spaceId, syncStatus, lastModified, simpleNoteId
      notes: 'id, userId, threadId, spaceId, syncStatus, lastModified, simpleNoteId, [userId+threadId], [userId+spaceId], [userId+syncStatus], [userId+simpleNoteId]',
      
      // NoteThreads junction: indexed by userId, noteId, threadId
      noteThreads: 'id, userId, noteId, threadId, [userId+noteId], [userId+threadId], [noteId+threadId]',
      
      // Tags: indexed by userId, tagId, syncStatus
      tags: 'id, userId, syncStatus, [userId+syncStatus]',
      
      // NoteTags junction: indexed by userId, noteId, tagId
      noteTags: 'id, userId, noteId, tagId, [userId+noteId], [userId+tagId]',
      
      // UserMetadata: indexed by userId (unique)
      userMetadata: 'id, userId',
      
      // Sync queue: indexed by userId, operation, entityType, entityId, timestamp
      syncQueue: '++id, userId, operation, entityType, entityId, timestamp, [userId+operation], [userId+entityType]',
      
      // Sync state: indexed by userId (unique)
      syncState: 'userId'
    });
  }
}

// Create singleton instance
export const offlineDB = new OfflineDatabase();

// Helper function to get user-specific data
export async function getUserId(): Promise<string | null> {
  // This will be set by the sync manager or auth context
  // For now, return null - will be implemented when we add auth integration
  return null;
}

// Helper function to ensure user partition
export function ensureUserPartition<T extends { userId: string }>(
  entity: Omit<T, 'userId'>,
  userId: string
): T {
  return { ...entity, userId } as T;
}

