import Dexie, { type Table } from 'dexie';

// Sync status for offline entities
export type SyncStatus = 'synced' | 'pending' | 'conflict' | 'deleted';

// Base interface for all offline entities
interface BaseOfflineEntity {
  id: string;
  userId: string; // Clerk user ID for partitioning
  syncStatus: SyncStatus;
  lastModified: number; // Timestamp for conflict resolution
  serverVersion?: number; // Server-side version/timestamp for conflict detection
  createdAt: Date;
  updatedAt: Date | null;
}

// Offline Space entity
export interface OfflineSpace extends BaseOfflineEntity {
  title: string;
  description: string | null;
  color: string | null;
  backgroundGradient: string | null;
  isPublic: boolean;
  isActive: boolean;
  order: number;
}

// Offline Thread entity
export interface OfflineThread extends BaseOfflineEntity {
  title: string;
  subtitle: string | null;
  spaceId: string | null;
  color: string | null;
  isPublic: boolean;
  isPinned: boolean;
  order: number;
  lastVisited: Date | null;
}

// Offline Note entity
export interface OfflineNote extends BaseOfflineEntity {
  /** Immutable canonical version expected by the next queued content mutation. */
  currentVersion?: number;
  title: string | null;
  content: string;
  contentEncrypted?: boolean;
  threadId: string; // Legacy field (always 'thread_unorganized')
  spaceId: string | null;
  simpleNoteId: number | null;
  noteType: 'default' | 'scripture' | 'resource';
  addedBy: string;
  isPublic: boolean;
  isFeatured: boolean;
  order: number;
  lastVisited: Date | null;
  linkedFromNoteId?: string | null;
}

// Offline NoteThread junction entity
export interface OfflineNoteThread extends BaseOfflineEntity {
  noteId: string;
  threadId: string;
}

// Offline NoteConnection graph edge
export interface OfflineNoteConnection extends BaseOfflineEntity {
  fromNoteId: string;
  toNoteId: string;
  spaceId: string | null;
}

// Offline Tag entity
export interface OfflineTag extends BaseOfflineEntity {
  name: string;
  color: string | null;
  category: string | null;
  isSystem: boolean;
}

// Offline NoteTag junction entity
export interface OfflineNoteTag extends BaseOfflineEntity {
  noteId: string;
  tagId: string;
  isAutoGenerated: boolean;
  confidence: number | null;
}

// Offline UserMetadata entity
export interface OfflineUserMetadata extends BaseOfflineEntity {
  highestSimpleNoteId: number;
  reservedSimpleNoteIdRange: { start: number; end: number } | null; // Reserved range for offline allocation
  usedReservedIds: number[]; // Track which IDs from reserved range have been used
  userColor: string;
  firstName: string | null;
  lastName: string | null;
  email: string | null;
  profileImageUrl: string | null;
  clerkDataUpdatedAt: Date | null;
  churchName: string | null;
  churchCity: string | null;
  churchState: string | null;
  churchCountry: string | null;
  currentSeason: string | null;
  lastMonthlyVisit: Date | null;
  churchAddedAt: Date | null;
  /** Account-synced appearance preferences (JSON string) or null if never set. */
  appearanceSettings: string | null;
}

// Sync operation for mutation queue
export interface SyncOperation {
  id?: number; // Auto-increment primary key
  userId: string; // Clerk user ID
  operation: 'create' | 'update' | 'delete';
  entityType: 'space' | 'thread' | 'note' | 'noteThread' | 'tag' | 'noteTag';
  entityId: string; // Local ID (may be replaced with server ID after sync)
  data: any; // Full entity data or partial update
  timestamp: number; // When the operation was queued
  retryCount: number; // Number of retry attempts
  lastError?: string; // Last error message if sync failed
  serverId?: string; // Server-assigned ID after successful sync
  clientMutationId?: string; // UUID for server-side idempotency (prevents duplicates on retry)
}

// Sync state for tracking sync progress
export interface SyncState {
  userId: string; // Clerk user ID (primary key)
  lastSyncCursor: string | null; // Cursor for incremental sync
  lastSyncTimestamp: number | null; // Last successful sync timestamp
  lastBootstrapTimestamp: number | null; // When bootstrap was last completed
  isSyncing: boolean; // Whether sync is currently in progress
  syncError: string | null; // Last sync error
  lastCacheUpdate?: number; // Timestamp of last service worker cache update
  cacheSize?: number; // Estimated cache size in bytes (optional)
}

// Thread cache entry for caching thread content
export interface ThreadCacheEntry {
  threadId: string;
  userId: string;
  data: {
    thread: any;
    notes: any[];
    noteTypeCounts: {
      all: number;
      default: number;
      scripture: number;
      resource: number;
    };
  };
  timestamp: number;
  expiresAt: number;
}

// Offline database class
class OfflineDatabase extends Dexie {
  spaces!: Table<OfflineSpace>;
  threads!: Table<OfflineThread>;
  notes!: Table<OfflineNote>;
  noteThreads!: Table<OfflineNoteThread>;
  noteConnections!: Table<OfflineNoteConnection>;
  tags!: Table<OfflineTag>;
  noteTags!: Table<OfflineNoteTag>;
  userMetadata!: Table<OfflineUserMetadata>;
  syncQueue!: Table<SyncOperation>;
  syncState!: Table<SyncState>;
  threadCache!: Table<ThreadCacheEntry>;

  constructor() {
    super('HarvousOfflineDB');
    
    // Define schema with indexes for efficient queries
    // Version 2: Initial schema
    this.version(2).stores({
      // Spaces: indexed by userId, spaceId, syncStatus, lastModified
      spaces: 'id, userId, syncStatus, lastModified, [userId+syncStatus], [userId+id]',
      
      // Threads: indexed by userId, threadId, spaceId, syncStatus, lastModified
      threads: 'id, userId, spaceId, syncStatus, lastModified, [userId+spaceId], [userId+syncStatus], [userId+id]',
      
      // Notes: indexed by userId, noteId, threadId, spaceId, syncStatus, lastModified, simpleNoteId
      notes: 'id, userId, threadId, spaceId, syncStatus, lastModified, simpleNoteId, [userId+threadId], [userId+spaceId], [userId+syncStatus], [userId+simpleNoteId], [userId+id]',
      
      // NoteThreads junction: indexed by userId, noteId, threadId
      noteThreads: 'id, userId, noteId, threadId, [userId+noteId], [userId+threadId], [noteId+threadId], [userId+noteId+threadId], [userId+id]',
      
      // Tags: indexed by userId, tagId, syncStatus
      tags: 'id, userId, syncStatus, [userId+syncStatus], [userId+id]',
      
      // NoteTags junction: indexed by userId, noteId, tagId
      noteTags: 'id, userId, noteId, tagId, [userId+noteId], [userId+tagId], [userId+id]',
      
      // UserMetadata: indexed by userId (unique)
      userMetadata: 'id, userId, [userId+id]',
      
      // Sync queue: indexed by userId, operation, entityType, entityId, timestamp
      syncQueue: '++id, userId, operation, entityType, entityId, timestamp, [userId+operation], [userId+entityType], [userId+id]',
      
      // Sync state: indexed by userId (unique)
      syncState: 'userId'
    });

    // Version 3: Add thread cache table
    this.version(3).stores({
      // Keep all existing tables
      spaces: 'id, userId, syncStatus, lastModified, [userId+syncStatus], [userId+id]',
      threads: 'id, userId, spaceId, syncStatus, lastModified, [userId+spaceId], [userId+syncStatus], [userId+id]',
      notes: 'id, userId, threadId, spaceId, syncStatus, lastModified, simpleNoteId, [userId+threadId], [userId+spaceId], [userId+syncStatus], [userId+simpleNoteId], [userId+id]',
      noteThreads: 'id, userId, noteId, threadId, [userId+noteId], [userId+threadId], [noteId+threadId], [userId+noteId+threadId], [userId+id]',
      tags: 'id, userId, syncStatus, [userId+syncStatus], [userId+id]',
      noteTags: 'id, userId, noteId, tagId, [userId+noteId], [userId+tagId], [userId+id]',
      userMetadata: 'id, userId, [userId+id]',
      syncQueue: '++id, userId, operation, entityType, entityId, timestamp, [userId+operation], [userId+entityType], [userId+id]',
      syncState: 'userId',
      // Add new thread cache table
      threadCache: '[threadId+userId], threadId, userId, timestamp, expiresAt'
    });

    // Version 4: NoteConnections graph for prototype study threads / offline parity
    this.version(4).stores({
      spaces: 'id, userId, syncStatus, lastModified, [userId+syncStatus], [userId+id]',
      threads: 'id, userId, spaceId, syncStatus, lastModified, [userId+spaceId], [userId+syncStatus], [userId+id]',
      notes: 'id, userId, threadId, spaceId, syncStatus, lastModified, simpleNoteId, [userId+threadId], [userId+spaceId], [userId+syncStatus], [userId+simpleNoteId], [userId+id]',
      noteThreads: 'id, userId, noteId, threadId, [userId+noteId], [userId+threadId], [noteId+threadId], [userId+noteId+threadId], [userId+id]',
      noteConnections:
        'id, userId, fromNoteId, toNoteId, spaceId, [userId+fromNoteId], [userId+toNoteId], [userId+id]',
      tags: 'id, userId, syncStatus, [userId+syncStatus], [userId+id]',
      noteTags: 'id, userId, noteId, tagId, [userId+noteId], [userId+tagId], [userId+id]',
      userMetadata: 'id, userId, [userId+id]',
      syncQueue: '++id, userId, operation, entityType, entityId, timestamp, [userId+operation], [userId+entityType], [userId+id]',
      syncState: 'userId',
      threadCache: '[threadId+userId], threadId, userId, timestamp, expiresAt'
    });
  }
}

// Create singleton instance
export const offlineDB = new OfflineDatabase();

/**
 * Ensure database is open, reopen if closed
 * This is necessary because the database can be closed after deletion or other operations
 */
export async function ensureDatabaseOpen(): Promise<void> {
  try {
    // Check if database is already open
    if (offlineDB.isOpen()) {
      return;
    }
    
    // Database appears closed, try to reopen it silently
    // Note: isOpen() can be unreliable in Dexie, so we don't warn here
    // Only log warnings/errors when reopening actually fails
    await offlineDB.open();
  } catch (error: any) {
    // If open fails, it might be because the database was deleted
    // Try to open again - Dexie will recreate the database if needed
    if (error?.name === 'DatabaseClosedError' || error?.message?.includes('closed')) {
      console.warn('[ensureDatabaseOpen] Database open failed, retrying...', error);
      try {
        await offlineDB.open();
      } catch (retryError) {
        console.error('[ensureDatabaseOpen] Failed to reopen database after retry:', retryError);
        throw retryError;
      }
    } else {
      // Only log unexpected errors
      console.error('[ensureDatabaseOpen] Unexpected error opening database:', error);
      throw error;
    }
  }
}

// Helper function to retry IndexedDB operations with exponential backoff
export async function retryIndexedDBOperation<T>(
  operation: () => Promise<T>,
  maxRetries: number = 3,
  baseDelay: number = 100
): Promise<T> {
  let lastError: Error | null = null;
  
  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      return await operation();
    } catch (error: any) {
      lastError = error;
      
      // Check if it's a quota error - these are usually permanent
      if (error?.name === 'QuotaExceededError') {
        console.error('[retryIndexedDBOperation] Quota exceeded, cannot retry:', error);
        throw error;
      }
      
      // Check if it's a connection error - reopen database and retry with backoff
      if (error?.name === 'DatabaseClosedError' || error?.message?.includes('closed')) {
        const delay = baseDelay * Math.pow(2, attempt);
        console.warn(`[retryIndexedDBOperation] Database closed, reopening and retrying in ${delay}ms (attempt ${attempt + 1}/${maxRetries})`);
        
        // Try to reopen the database before retrying
        try {
          await ensureDatabaseOpen();
        } catch (reopenError) {
          console.error('[retryIndexedDBOperation] Failed to reopen database:', reopenError);
          // Continue with retry anyway - the operation might succeed if database opens during delay
        }
        
        await new Promise(resolve => setTimeout(resolve, delay));
        continue;
      }
      
      // For other errors, retry once more
      if (attempt < maxRetries - 1) {
        const delay = baseDelay * Math.pow(2, attempt);
        console.warn(`[retryIndexedDBOperation] Operation failed, retrying in ${delay}ms (attempt ${attempt + 1}/${maxRetries}):`, error);
        await new Promise(resolve => setTimeout(resolve, delay));
        continue;
      }
      
      // Last attempt failed
      throw error;
    }
  }
  
  throw lastError || new Error('Operation failed after retries');
}

/**
 * localStorage cache key prefix for highestSimpleNoteId
 */
const HIGHEST_NOTE_ID_KEY = 'harvous_highestSimpleNoteId';

/**
 * Cache the highest simple note ID in localStorage for instant offline access
 */
export function cacheHighestSimpleNoteId(userId: string, id: number): void {
  try {
    localStorage.setItem(`${HIGHEST_NOTE_ID_KEY}_${userId}`, String(id));
  } catch (error) {
    console.warn('[cacheHighestSimpleNoteId] Failed to cache ID:', error);
  }
}

/**
 * Get the cached highest simple note ID from localStorage
 */
export function getCachedHighestSimpleNoteId(userId: string): number | null {
  try {
    const cached = localStorage.getItem(`${HIGHEST_NOTE_ID_KEY}_${userId}`);
    return cached ? parseInt(cached, 10) : null;
  } catch (error) {
    console.warn('[getCachedHighestSimpleNoteId] Failed to read cache:', error);
    return null;
  }
}

// Helper function to get user-specific data
export async function getUserId(): Promise<string | null> {
  // This will be set by the sync manager or auth context
  // For now, return null - will be implemented when we add auth integration
  return null;
}

// Helper function to ensure user partition
export function ensureUserPartition<T extends { userId: string }>(
  entity: Omit<T, 'userId'>,
  userId: string
): T {
  return { ...entity, userId } as T;
}

