import { describe, expect, it } from 'vitest';
import { dedupeNoteTagsForResponse } from '../tag-helpers';

/**
 * `ts()` columns are declared `mode: 'date'`, so a tag row read from the database carries
 * a real `Date` in `createdAt` — but the row types used to declare `string`, and the
 * dedupe tie-breaker called `Date.parse(row.createdAt)`.
 *
 * `Date.parse` takes a string, so a `Date` argument is coerced through `toString()`, which
 * only has second precision. Two tags created in the same second therefore compared as
 * equal and fell through to id ordering instead of creation order.
 */
describe('dedupeNoteTagsForResponse createdAt ordering', () => {
  const sameSecond = (ms: number) => new Date(`2026-08-03T12:00:00.${ms}Z`);

  it('prefers the earlier tag when both were created in the same second', () => {
    // Ids are chosen so id-ordering would pick the *later* tag — if the timestamp
    // comparison silently ties, this test fails.
    const [kept] = dedupeNoteTagsForResponse([
      { id: 'zzz-earlier', name: 'Grace', createdAt: sameSecond(100) },
      { id: 'aaa-later', name: 'grace', createdAt: sameSecond(900) },
    ]);
    expect(kept.id).toBe('zzz-earlier');
  });

  it('still orders correctly across different seconds', () => {
    const [kept] = dedupeNoteTagsForResponse([
      { id: 'b', name: 'Grace', createdAt: new Date('2026-08-03T12:00:05.000Z') },
      { id: 'a', name: 'grace', createdAt: new Date('2026-08-03T12:00:01.000Z') },
    ]);
    expect(kept.id).toBe('a');
  });

  it('accepts ISO strings too, for callers rehydrating from JSON', () => {
    const [kept] = dedupeNoteTagsForResponse([
      { id: 'zzz-earlier', name: 'Grace', createdAt: '2026-08-03T12:00:00.100Z' },
      { id: 'aaa-later', name: 'grace', createdAt: '2026-08-03T12:00:00.900Z' },
    ]);
    expect(kept.id).toBe('zzz-earlier');
  });

  it('prefers a user-assigned tag over an auto-generated one regardless of time', () => {
    const [kept] = dedupeNoteTagsForResponse([
      { id: 'auto', name: 'Grace', isAutoGenerated: true, createdAt: sameSecond(100) },
      { id: 'user', name: 'grace', isAutoGenerated: false, createdAt: sameSecond(900) },
    ]);
    expect(kept.id).toBe('user');
  });

  it('treats a missing createdAt as last', () => {
    const [kept] = dedupeNoteTagsForResponse([
      { id: 'zzz-no-date', name: 'Grace', createdAt: null },
      { id: 'aaa-dated', name: 'grace', createdAt: sameSecond(500) },
    ]);
    expect(kept.id).toBe('aaa-dated');
  });
});
