-- Enable Row Level Security on all tables.
-- The service_role key bypasses RLS, so no policies are needed.
-- This blocks anonymous/anon-key access by default.

ALTER TABLE "Spaces" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Threads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NoteThreads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Comments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SpaceInvitations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserMetadata" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClerkUserMapping" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserXP" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserSeasonalXP" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserLifetimeXP" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WeeklyStreaks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NoteTags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ScriptureMetadata" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NoteScriptureReferences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerseTextCache" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ResourceMetadata" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InboxItems" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InboxItemNotes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserInboxItems" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MonthlyAnalytics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FeaturedItems" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserFeaturedItems" ENABLE ROW LEVEL SECURITY;
