/**
 * One-time migration: Turso (SQLite) → Supabase (Postgres).
 *
 * Reads all data from the Turso database via direct SQL, transforms dates
 * from ISO strings to Date objects, and bulk-inserts into Supabase via Drizzle.
 *
 * Usage:
 *   npx tsx scripts/migrate-turso-to-supabase.ts
 *
 * Requires in .env:
 *   TURSO_DATABASE_URL, TURSO_AUTH_TOKEN (source)
 *   SUPABASE_DATABASE_URL (destination — pooler URL, port 6543)
 *   SUPABASE_DIRECT_URL (destination — direct URL, port 5432, for drizzle-kit push)
 *
 * Steps:
 *   1. Push schema to Supabase (drizzle-kit push)
 *   2. Read all rows from Turso
 *   3. Transform date strings → Date objects
 *   4. Batch-insert into Supabase in dependency order
 *   5. Verify row counts match
 */
import 'dotenv/config';
import { createClient } from '@libsql/client';
import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
import { sql } from 'drizzle-orm';
import * as schema from '../server/db/schema';

// ─── Configuration ──────────────────────────────────────────────────────────────

const BATCH_SIZE = 100;

// Tables in dependency order (parents first, junction tables last)
const TABLE_ORDER = [
  'UserMetadata',
  'ClerkUserMapping',
  'Spaces',
  'Threads',
  'Notes',
  'NoteThreads',
  'Comments',
  'Members',
  'SpaceInvitations',
  'UserXP',
  'UserSeasonalXP',
  'UserLifetimeXP',
  'WeeklyStreaks',
  'Tags',
  'NoteTags',
  'ScriptureMetadata',
  'NoteScriptureReferences',
  'VerseTextCache',
  'ResourceMetadata',
  'InboxItems',
  'InboxItemNotes',
  'UserInboxItems',
  'MonthlyAnalytics',
] as const;

// Date columns per table (columns stored as ISO text in SQLite, need → Date for Postgres)
const DATE_COLUMNS: Record<string, string[]> = {
  Spaces: ['createdAt', 'updatedAt', 'lastVisited', 'shareTokenCreatedAt'],
  Threads: ['createdAt', 'updatedAt', 'lastVisited', 'shareTokenCreatedAt'],
  Notes: ['createdAt', 'updatedAt', 'lastVisited', 'shareTokenCreatedAt'],
  NoteThreads: ['createdAt'],
  Comments: ['createdAt', 'updatedAt'],
  Members: ['createdAt', 'joinedAt'],
  SpaceInvitations: ['expiresAt', 'createdAt', 'acceptedAt'],
  UserMetadata: ['clerkDataUpdatedAt', 'lastMonthlyVisit', 'churchAddedAt', 'createdAt', 'updatedAt'],
  ClerkUserMapping: ['migratedToLiveAt'],
  UserXP: ['createdAt'],
  UserSeasonalXP: ['createdAt', 'updatedAt'],
  UserLifetimeXP: ['lastUpdated'],
  WeeklyStreaks: ['weekStart', 'createdAt', 'updatedAt'],
  Tags: ['createdAt', 'updatedAt'],
  NoteTags: ['createdAt'],
  ScriptureMetadata: ['createdAt'],
  NoteScriptureReferences: ['createdAt'],
  VerseTextCache: ['createdAt'],
  ResourceMetadata: ['createdAt'],
  InboxItems: ['createdAt', 'updatedAt'],
  InboxItemNotes: ['createdAt'],
  UserInboxItems: ['addedAt', 'archivedAt', 'createdAt'],
  MonthlyAnalytics: ['createdAt', 'updatedAt'],
};

// Boolean columns per table (stored as 0/1 integers in SQLite, need → boolean for Postgres)
const BOOLEAN_COLUMNS: Record<string, string[]> = {
  Spaces: ['isPublic', 'isActive'],
  Threads: ['isPublic', 'isPinned'],
  Notes: ['isPublic', 'isFeatured', 'contentEncrypted'],
  Tags: ['isSystem'],
  NoteTags: ['isAutoGenerated'],
  InboxItems: ['isActive'],
};

// Schema table map for Drizzle inserts
const SCHEMA_MAP: Record<string, any> = {
  UserMetadata: schema.UserMetadata,
  ClerkUserMapping: schema.ClerkUserMapping,
  Spaces: schema.Spaces,
  Threads: schema.Threads,
  Notes: schema.Notes,
  NoteThreads: schema.NoteThreads,
  Comments: schema.Comments,
  Members: schema.Members,
  SpaceInvitations: schema.SpaceInvitations,
  UserXP: schema.UserXP,
  UserSeasonalXP: schema.UserSeasonalXP,
  UserLifetimeXP: schema.UserLifetimeXP,
  WeeklyStreaks: schema.WeeklyStreaks,
  Tags: schema.Tags,
  NoteTags: schema.NoteTags,
  ScriptureMetadata: schema.ScriptureMetadata,
  NoteScriptureReferences: schema.NoteScriptureReferences,
  VerseTextCache: schema.VerseTextCache,
  ResourceMetadata: schema.ResourceMetadata,
  InboxItems: schema.InboxItems,
  InboxItemNotes: schema.InboxItemNotes,
  UserInboxItems: schema.UserInboxItems,
  MonthlyAnalytics: schema.MonthlyAnalytics,
};

// ─── Connections ────────────────────────────────────────────────────────────────

function connectTurso() {
  const url = process.env.TURSO_DATABASE_URL ?? process.env.ASTRO_DB_REMOTE_URL;
  const authToken = process.env.TURSO_AUTH_TOKEN ?? process.env.ASTRO_DB_APP_TOKEN;
  if (!url || !authToken) throw new Error('Missing TURSO_DATABASE_URL and TURSO_AUTH_TOKEN');
  return createClient({ url, authToken });
}

function connectSupabase() {
  // Use direct URL (port 5432) for migration — pooler (6543) has connectivity issues
  const url = process.env.SUPABASE_DIRECT_URL ?? process.env.SUPABASE_DATABASE_URL;
  if (!url) throw new Error('Missing SUPABASE_DIRECT_URL or SUPABASE_DATABASE_URL');
  const client = postgres(url, { max: 5, idle_timeout: 30, connect_timeout: 30 });
  return drizzle(client, { schema });
}

// ─── Transform ──────────────────────────────────────────────────────────────────

function transformRow(tableName: string, row: Record<string, any>): Record<string, any> {
  const dateCols = DATE_COLUMNS[tableName] || [];
  const boolCols = BOOLEAN_COLUMNS[tableName] || [];
  const transformed = { ...row };

  // Convert all values: bigint → number (libsql returns bigint for integers)
  for (const key of Object.keys(transformed)) {
    if (typeof transformed[key] === 'bigint') {
      transformed[key] = Number(transformed[key]);
    }
  }

  for (const col of dateCols) {
    const val = transformed[col];
    if (val == null || val === '') {
      transformed[col] = null; // empty string → null for timestamps
    } else if (typeof val === 'string') {
      const d = new Date(val);
      transformed[col] = isNaN(d.getTime()) ? null : d;
    }
  }

  for (const col of boolCols) {
    if (transformed[col] != null) {
      transformed[col] = Boolean(transformed[col]);
    }
  }

  return transformed;
}

// ─── Batch insert ───────────────────────────────────────────────────────────────

async function batchInsert(db: ReturnType<typeof connectSupabase>, tableName: string, rows: Record<string, any>[]) {
  const table = SCHEMA_MAP[tableName];
  if (!table) throw new Error(`Unknown table: ${tableName}`);

  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);
    try {
      await db.insert(table).values(batch).onConflictDoNothing();
    } catch (err: any) {
      // Log the failing batch for debugging
      console.error(`\n  ✗ ${tableName} batch ${i}-${i + batch.length} failed:`);
      // Show the actual Postgres error (nested in cause)
      const cause = err.cause || err;
      console.error(`    Error: ${cause.message?.slice(0, 500)}`);
      if (cause.detail) console.error(`    Detail: ${cause.detail}`);
      if (cause.code) console.error(`    Code: ${cause.code}`);
      if (cause.column) console.error(`    Column: ${cause.column}`);
      console.error(`    First row keys:`, Object.keys(batch[0]));
      // Show date columns for debugging
      const dateCols = DATE_COLUMNS[tableName] || [];
      for (const col of dateCols) {
        const val = batch[0][col];
        console.error(`    ${col}: ${val} (type: ${typeof val}, isDate: ${val instanceof Date})`);
      }
      throw err;
    }
    process.stdout.write(`  ${tableName}: ${Math.min(i + BATCH_SIZE, rows.length)}/${rows.length}\r`);
  }
  console.log(`  ${tableName}: ${rows.length} rows inserted`);
}

// ─── Main ───────────────────────────────────────────────────────────────────────

async function main() {
  console.log('=== Turso → Supabase Migration ===\n');

  // 1. Connect to both databases
  console.log('Connecting to Turso (source)...');
  const turso = connectTurso();

  console.log('Connecting to Supabase (destination)...');
  const supabase = connectSupabase();

  // 2. Read and migrate each table
  const counts: Record<string, { turso: number; supabase: number }> = {};

  for (const tableName of TABLE_ORDER) {
    console.log(`\nMigrating ${tableName}...`);

    // Read from Turso
    const result = await turso.execute(`SELECT * FROM "${tableName}"`);
    const rows = result.rows as unknown as Record<string, any>[];
    counts[tableName] = { turso: rows.length, supabase: 0 };

    if (rows.length === 0) {
      console.log(`  ${tableName}: 0 rows (skipping)`);
      continue;
    }

    // Transform dates and booleans
    const transformed = rows.map(row => transformRow(tableName, row));

    // Insert into Supabase
    await batchInsert(supabase, tableName, transformed);
    counts[tableName].supabase = rows.length;
  }

  // 3. Verify row counts
  console.log('\n=== Verification ===\n');
  let allMatch = true;

  for (const tableName of TABLE_ORDER) {
    const table = SCHEMA_MAP[tableName];
    const [{ count: pgCount }] = await supabase
      .select({ count: sql<number>`count(*)` })
      .from(table);

    const tursoCount = counts[tableName].turso;
    const match = Number(pgCount) >= tursoCount;
    const status = match ? '✓' : '✗';
    console.log(`  ${status} ${tableName}: Turso=${tursoCount}, Supabase=${pgCount}`);

    if (!match) allMatch = false;
  }

  console.log(allMatch ? '\n✓ All row counts match!' : '\n✗ Some row counts do not match — investigate before proceeding.');

  // 4. Cleanup
  turso.close();
  process.exit(allMatch ? 0 : 1);
}

main().catch((err) => {
  console.error('Migration failed:', err);
  process.exit(1);
});
