import React, { useState, useEffect } from 'react';
import SquareButton from './SquareButton';
import { toast } from '@/utils/toast';

interface NewTagPanelProps {
  noteId: string;
  onClose: () => void;
  onTagCreated?: () => void;
  inBottomSheet?: boolean;
  inline?: boolean; // If true, render as inline form without panel wrapper
  /** Visible placeholder on the tag name input (Note Details sticky composer defaults this). */
  placeholder?: string;
}

export default function NewTagPanel({
  noteId,
  onClose,
  onTagCreated,
  inBottomSheet = false,
  inline = false,
  placeholder = 'Enter tag name'
}: NewTagPanelProps) {
  const [tagName, setTagName] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  // Initialize isMobile immediately to prevent autoFocus on first render
  const [isMobile, setIsMobile] = useState(() => {
    if (typeof window !== 'undefined') {
      return window.innerWidth < 1160;
    }
    // Default to true (mobile) for SSR safety
    return true;
  });

  // Check if we're on mobile (viewport width < 1160px) and handle resize
  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 1160);
    };
    // Re-check on mount in case initial state was wrong
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    e.stopPropagation();
    
    // Validate tag name
    const trimmedName = tagName.trim();
    if (!trimmedName) {
      toast.error('Tag name is required');
      return;
    }

    setIsSubmitting(true);
    
    try {
      let tagId: string;
      
      // Step 1: Try to create the tag
      const createResponse = await fetch('/api/tags/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: trimmedName,
          color: '#006eff',
          category: 'spiritual'
        }),
        credentials: 'include'
      });

      if (!createResponse.ok) {
        const error = await createResponse.json();
        if (createResponse.status === 409) {
          // Tag already exists - find it and use its ID
          const listResponse = await fetch('/api/tags/list', {
            credentials: 'include'
          });
          
          if (!listResponse.ok) {
            toast.error('Error finding existing tag');
            setIsSubmitting(false);
            return;
          }
          
          const listResult = await listResponse.json();
          const existingTag = listResult.tags?.find((tag: any) => 
            tag.name.toLowerCase() === trimmedName.toLowerCase()
          );
          
          if (!existingTag) {
            toast.error('Tag already exists but could not be found');
            setIsSubmitting(false);
            return;
          }
          
          tagId = existingTag.id;
        } else {
          toast.error(error.error || 'Error creating tag');
          setIsSubmitting(false);
          return;
        }
      } else {
        const createResult = await createResponse.json();
        tagId = createResult.tag.id;
      }

      // Step 2: Assign tag to note
      const assignResponse = await fetch('/api/note-tags/assign', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          noteId: noteId,
          tagId: tagId,
          isAutoGenerated: false
        }),
        credentials: 'include'
      });

      if (!assignResponse.ok) {
        const error = await assignResponse.json();
        if (assignResponse.status === 409) {
          // Tag already assigned to note - this is fine, just refresh
          toast.success(`"${trimmedName}" is already on this note`);
          setTagName('');
          
          // Call callback to refresh tag list
          if (onTagCreated) {
            onTagCreated();
          }
        } else {
          toast.error(error.error || 'Error assigning tag to note');
        }
        setIsSubmitting(false);
        return;
      }

      // Success!
      toast.success(`Added "${trimmedName}" to this note`);
      setTagName('');
      
      // Call callback to refresh tag list
      if (onTagCreated) {
        onTagCreated();
      }
      
      // Close panel only if not inline mode
      if (!inline) {
        onClose();
      }
    } catch (error) {
      console.error('Error creating tag:', error);
      toast.error('Error creating tag. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Inline mode - render just the form without panel wrapper
  if (inline) {
    return (
      <form onSubmit={handleSubmit} className="w-full flex-stack">
        {/* Text input field */}
        <div className="search-input w-full">
          <input
            type="text"
            value={tagName}
            onChange={(e) => setTagName(e.target.value)}
            placeholder={placeholder}
            className="search-input__field"
            disabled={isSubmitting}
            autoFocus={!isMobile}
            autoComplete="off"
            aria-label="New tag name"
          />
        </div>

        {/* Add Tag button */}
        <button
          type="submit"
          disabled={isSubmitting}
          data-outer-shadow
          className="btn-cta btn--secondary w-full group"
        >
          <span className="btn-cta__content">
            {isSubmitting ? 'Adding...' : 'Add tag'}
          </span>
          <div className="btn-cta__shadow" />
        </button>
      </form>
    );
  }

  // Full panel mode
  return (
    <div className={`panel-wrapper ${inBottomSheet ? 'panel-wrapper--bottom-sheet' : ''}`}>
      <form onSubmit={handleSubmit} className="flex-fill flex-stack" style={{ gap: 0 }}>
        {/* Content area - expands on mobile, fits content on desktop */}
        <div className={inBottomSheet ? "flex-fill flex-stack" : "flex-stack"} style={{ gap: 0 }}>
          {/* Panel container */}
          <div className={`panel ${inBottomSheet ? 'panel--bottom-sheet' : ''}`}>
            {/* Header section */}
            <div className="panel__header">
              <div className="panel__title">
                <p>New Tag</p>
              </div>
            </div>
            
            {/* Content area */}
            <div className={`panel__body ${inBottomSheet ? 'panel__body--bottom-sheet' : ''}`}>
              <div className={`panel__content ${inBottomSheet ? 'panel__content--bottom-sheet' : ''}`}>
                <div className="panel__content-scroll">
                <div className="w-full">
                  
                  {/* Text input field */}
                  <div className="search-input w-full">
                    <input
                      type="text"
                      value={tagName}
                      onChange={(e) => setTagName(e.target.value)}
                      placeholder={placeholder}
                      className="search-input__field"
                      disabled={isSubmitting}
                      autoFocus={!isMobile}
                      autoComplete="off"
                      aria-label="New tag name"
                    />
                  </div>

                  {/* Add Tag button - inside content area */}
                  <button
                    type="submit"
                    disabled={isSubmitting}
                    data-outer-shadow
                    className="btn-cta btn--secondary w-full group"
                  >
                    <span className="btn-cta__content">
                      {isSubmitting ? 'Adding...' : 'Add tag'}
                    </span>
                    <div className="btn-cta__shadow" />
                  </button>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom buttons - only back arrow */}
        <div className="panel__footer--buttons">
          {/* Back button - SquareButton Back variant */}
          <SquareButton 
            variant="Back"
            onClick={onClose}
            inBottomSheet={inBottomSheet}
          />
        </div>
      </form>
    </div>
  );
}

