import React, { useState } from 'react';
import SquareButton from './SquareButton';
import { toast } from '@/utils/toast';

interface NewTagPanelProps {
  noteId: string;
  onClose: () => void;
  onTagCreated?: () => void;
  inBottomSheet?: boolean;
}

export default function NewTagPanel({
  noteId,
  onClose,
  onTagCreated,
  inBottomSheet = false
}: NewTagPanelProps) {
  const [tagName, setTagName] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    e.stopPropagation();
    
    console.log('NewTagPanel: Form submitted, tagName:', tagName);
    
    // Validate tag name
    const trimmedName = tagName.trim();
    if (!trimmedName) {
      toast.error('Tag name is required');
      return;
    }

    setIsSubmitting(true);
    
    try {
      // Step 1: Create the tag
      const createResponse = await fetch('/api/tags/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: trimmedName,
          color: '#006eff',
          category: 'spiritual'
        }),
        credentials: 'include'
      });

      if (!createResponse.ok) {
        const error = await createResponse.json();
        if (createResponse.status === 409) {
          toast.error('Tag already exists');
        } else {
          toast.error(error.error || 'Error creating tag');
        }
        setIsSubmitting(false);
        return;
      }

      const createResult = await createResponse.json();
      const newTagId = createResult.tag.id;

      // Step 2: Assign tag to note
      const assignResponse = await fetch('/api/note-tags/assign', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          noteId: noteId,
          tagId: newTagId,
          isAutoGenerated: false
        }),
        credentials: 'include'
      });

      if (!assignResponse.ok) {
        const error = await assignResponse.json();
        if (assignResponse.status === 409) {
          toast.error('Tag already assigned to note');
        } else {
          toast.error(error.error || 'Error assigning tag to note');
        }
        setIsSubmitting(false);
        return;
      }

      // Success!
      toast.success('Tag created and added to note');
      setTagName('');
      
      // Call callback to refresh tag list
      if (onTagCreated) {
        onTagCreated();
      }
      
      // Close panel
      onClose();
    } catch (error) {
      console.error('Error creating tag:', error);
      toast.error('Error creating tag. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="h-full flex flex-col">
      <form onSubmit={handleSubmit} className="flex-1 flex flex-col">
        {/* Content area that expands to fill available space */}
        <div className="flex-1 flex flex-col min-h-0 mb-3.5">
          {/* Single unified panel using CardStack structure */}
          <div className="box-border content-stretch flex flex-col items-start justify-start overflow-clip pb-6 pt-0 px-0 relative rounded-3xl shadow-[0px_3px_20px_0px_rgba(120,118,111,0.1)] size-full">
            {/* Header section with paper background */}
            <div className="box-border content-stretch flex gap-3 items-center justify-center leading-[0] mb-[-24px] not-italic pb-12 pt-6 px-6 relative shrink-0 text-[var(--color-deep-grey)] w-full" style={{ backgroundColor: 'var(--color-paper)' }}>
              <div className="basis-0 font-sans font-bold grow min-h-px min-w-px relative shrink-0 text-[24px] text-center">
                <p className="leading-[normal]">New Tag</p>
              </div>
            </div>
            
            {/* Content area */}
            <div className="basis-0 box-border content-stretch flex flex-col grow items-start justify-start mb-[-24px] min-h-px min-w-px overflow-clip relative shrink-0 w-full">
              <div className="basis-0 bg-[var(--color-snow-white)] box-border content-stretch flex flex-col gap-3 grow items-start justify-start min-h-px min-w-px overflow-x-clip overflow-y-auto p-[12px] relative rounded-tl-[24px] rounded-tr-[24px] shrink-0 w-full">
                <div className="basis-0 grow min-h-px min-w-px shrink-0 w-full">
                  
                  {/* Text input field - styled like tag button */}
                  <div className="mb-3 relative">
                    <div className="relative">
                      <input
                        type="text"
                        value={tagName}
                        onChange={(e) => setTagName(e.target.value)}
                        placeholder="Type here..."
                        className="space-button relative rounded-[12px] cursor-text transition-[scale,shadow] duration-300 pb-3 pl-4 pr-3 pt-[10px] w-full h-[60px] outline-none border-none text-[var(--color-deep-grey)] font-sans text-[18px] font-semibold placeholder:text-[var(--color-pebble-grey)] placeholder:opacity-50"
                        style={{ backgroundImage: 'var(--color-gradient-gray)' }}
                        disabled={isSubmitting}
                        autoFocus
                      />
                      {/* Inset shadow */}
                      <div className="absolute inset-0 pointer-events-none rounded-[12px] shadow-[0px_-3px_0px_0px_inset_rgba(176,176,176,0.25)]" />
                    </div>
                  </div>

                  {/* Button row */}
                  <div className="content-stretch flex gap-3 items-start relative shrink-0 w-full">
                    {/* SquareButton with down arrow (left) - use SquareButton component */}
                    <SquareButton
                      variant="Back"
                      onClick={onClose}
                      inBottomSheet={true}
                    />
                    
                    {/* Primary button "Add Tag" (right) */}
                    <button
                      type="submit"
                      disabled={isSubmitting}
                      className="basis-0 bg-[var(--color-bold-blue)] box-border content-stretch flex grow h-[60px] items-center justify-center min-h-px min-w-px overflow-clip pb-[28px] pt-6 px-6 relative rounded-[24px] shrink-0 cursor-pointer disabled:opacity-50 transition-[scale,shadow] duration-300"
                      data-outer-shadow
                    >
                      <div className="font-sans font-semibold leading-[0] relative shrink-0 text-[18px] text-nowrap whitespace-pre text-[var(--color-fog-white)]">
                        {isSubmitting ? 'Adding...' : 'Add Tag'}
                      </div>
                      <div className="absolute inset-0 pointer-events-none rounded-[24px] shadow-[0px_-4px_0px_0px_inset_rgba(0,0,0,0.1)]" />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom close button using SquareButton Back variant */}
        <div className="flex items-center justify-start gap-3">
          <SquareButton 
            variant="Back" 
            onClick={onClose}
            inBottomSheet={inBottomSheet}
          />
        </div>
      </form>
    </div>
  );
}

