/**
 * Post-insert enrichment for web import — matches create/update:
 * auto-tags + processScriptureReferences (pills / metadata).
 */

import { folderLabelsForTagExclusion } from '@/utils/bible-study-concept-overlaps';
import { generateAutoTags, applyAutoTags } from './auto-tag-generator';
import { processScriptureReferences } from './process-scripture-references';
import { autoTagExcludeNames, dismissedAutoTagsForNote, normalizeTagName } from './tag-helpers';

export interface ImportEnrichmentInput {
  noteId: string;
  userId: string;
  /** Thread id used for NoteThreads / scripture parent resolution (may be unorganized). */
  threadId: string;
  title: string | null;
  content: string;
  noteType: 'default' | 'scripture' | 'resource';
  primaryCollection: string | null;
  secondaryCollections: string[];
  /** Frontmatter/CSV tags already attached as manual (isAutoGenerated: false). */
  manualTagNames: string[];
  /** Portable frontmatter `refs` (and similar) not necessarily in the body. */
  additionalReferences?: string[];
  defaultTranslation: string;
}

export interface ImportEnrichmentResult {
  autoTagsApplied: number;
  scriptureResultCount: number;
}

/** Build exclude options for import auto-tagging (folders + dismissed + manual tag names). */
export function autoTagExcludeOptionsForImport(note: {
  primaryCollection?: string | null;
  secondaryCollections?: string[] | null;
  dismissedAutoTags?: string | null;
  manualTagNames?: string[];
}): { excludeLabels: string[]; excludeTagNames: string[] } {
  const folderLabels = folderLabelsForTagExclusion(
    note.primaryCollection ?? null,
    note.secondaryCollections ?? [],
  );
  const dismissed = dismissedAutoTagsForNote({ dismissedAutoTags: note.dismissedAutoTags ?? null });
  const manual = (note.manualTagNames ?? [])
    .map((t) => t.trim())
    .filter(Boolean);
  const excludeTagNames = autoTagExcludeNames(folderLabels, [...dismissed, ...manual]);
  return { excludeLabels: folderLabels, excludeTagNames };
}

/**
 * Run create/update-parity enrichment after a successful import insert.
 * Failures should be caught by the caller and recorded without rolling back the note.
 */
export async function enrichImportedNote(input: ImportEnrichmentInput): Promise<ImportEnrichmentResult> {
  let autoTagsApplied = 0;
  let scriptureResultCount = 0;

  if (input.noteType !== 'resource') {
    const excludes = autoTagExcludeOptionsForImport({
      primaryCollection: input.primaryCollection,
      secondaryCollections: input.secondaryCollections,
      manualTagNames: input.manualTagNames,
    });
    // Also exclude normalized manual names so overlap checks see them.
    const manualNormalized = input.manualTagNames
      .map((n) => normalizeTagName(n))
      .filter(Boolean) as string[];
    const excludeTagNames = [
      ...excludes.excludeTagNames,
      ...manualNormalized.filter((n) => !excludes.excludeTagNames.some((e) => normalizeTagName(e) === n)),
    ];
    const r = await generateAutoTags(input.title || '', input.content, input.userId, 0.7, {
      excludeLabels: excludes.excludeLabels,
      excludeTagNames,
    });
    if (r.suggestions.length > 0) {
      const applied = await applyAutoTags(input.noteId, r.suggestions, input.userId);
      autoTagsApplied = applied.applied;
    }
  }

  const scriptureThreadId =
    input.threadId && input.threadId !== 'thread_unorganized' ? input.threadId : undefined;
  const scriptureResult = await processScriptureReferences(
    input.noteId,
    input.userId,
    scriptureThreadId,
    input.content,
    input.defaultTranslation || 'NET',
    {
      additionalReferences: input.additionalReferences?.length ? input.additionalReferences : undefined,
    },
  );
  scriptureResultCount = scriptureResult.results?.length ?? 0;

  return { autoTagsApplied, scriptureResultCount };
}
