import { db, first, Tags, NoteTags, eq, and } from '../db';
import { nowISO } from '../db/dates';

export type TagRow = {
  id: string;
  name: string;
  color: string | null;
  category: string | null;
  userId: string;
  isSystem: boolean;
  createdAt: string;
  updatedAt: string | null;
};

export function normalizeTagName(name: string): string {
  return name.trim().toLowerCase();
}

export async function findTagByName(userId: string, name: string): Promise<TagRow | undefined> {
  const trimmed = name.trim();
  if (!trimmed) return undefined;
  const allUserTags = await db.select().from(Tags).where(eq(Tags.userId, userId));
  return allUserTags.find((t) => t.name.toLowerCase() === trimmed.toLowerCase());
}

export interface GetOrCreateTagOptions {
  color?: string | null;
  category?: string | null;
  isSystem?: boolean;
}

export interface GetOrCreateTagResult {
  tagId: string;
  created: boolean;
  tag: TagRow;
}

export async function getOrCreateTag(
  userId: string,
  name: string,
  opts?: GetOrCreateTagOptions,
): Promise<GetOrCreateTagResult> {
  const trimmed = name.trim();
  if (!trimmed) throw new Error('Tag name cannot be empty');

  const existing = await findTagByName(userId, trimmed);
  if (existing) {
    return { tagId: existing.id, created: false, tag: existing };
  }

  const tagId = `tag_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  await db.insert(Tags).values({
    id: tagId,
    name: trimmed,
    color: opts?.color ?? null,
    category: opts?.category ?? null,
    userId,
    isSystem: opts?.isSystem ?? false,
    createdAt: nowISO(),
  });

  const tag = first(await db.select().from(Tags).where(eq(Tags.id, tagId)).limit(1))!;
  return { tagId, created: true, tag };
}

export type NoteTagResponseRow = {
  id: string;
  name: string;
  isAutoGenerated?: boolean | null;
  createdAt?: string | null;
};

function pickPreferredTag<T extends NoteTagResponseRow>(a: T, b: T): T {
  const aAuto = a.isAutoGenerated === true;
  const bAuto = b.isAutoGenerated === true;
  if (aAuto !== bAuto) return aAuto ? b : a;

  const aCreated = a.createdAt ? Date.parse(a.createdAt) : Number.MAX_SAFE_INTEGER;
  const bCreated = b.createdAt ? Date.parse(b.createdAt) : Number.MAX_SAFE_INTEGER;
  if (aCreated !== bCreated) return aCreated < bCreated ? a : b;

  return a.id < b.id ? a : b;
}

/** One entry per normalized tag name; prefers user-assigned over auto-generated. */
export function dedupeNoteTagsForResponse<T extends NoteTagResponseRow>(tags: T[]): T[] {
  const byName = new Map<string, T>();
  for (const tag of tags) {
    const key = normalizeTagName(tag.name);
    if (!key) continue;
    const prev = byName.get(key);
    byName.set(key, prev ? pickPreferredTag(prev, tag) : tag);
  }

  const seen = new Set<string>();
  const out: T[] = [];
  for (const tag of tags) {
    const key = normalizeTagName(tag.name);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    const picked = byName.get(key);
    if (picked) out.push(picked);
  }
  return out;
}

export type NoteTagDetailRow = {
  id: string;
  name: string;
  color: string | null;
  category: string | null;
  isSystem: boolean;
  isAutoGenerated: boolean | null;
  confidence: number | null;
  createdAt: string;
};

/** Tags on a note for API responses (join Tags owned by note author). */
export async function fetchNoteTagsForResponse(
  noteId: string,
  noteOwnerUserId: string,
): Promise<NoteTagDetailRow[]> {
  const noteTags = await db
    .select({
      id: Tags.id,
      name: Tags.name,
      color: Tags.color,
      category: Tags.category,
      isSystem: Tags.isSystem,
      isAutoGenerated: NoteTags.isAutoGenerated,
      confidence: NoteTags.confidence,
      createdAt: NoteTags.createdAt,
    })
    .from(NoteTags)
    .innerJoin(Tags, eq(NoteTags.tagId, Tags.id))
    .where(and(eq(NoteTags.noteId, noteId), eq(Tags.userId, noteOwnerUserId)))
    .orderBy(Tags.name);
  return dedupeNoteTagsForResponse(noteTags);
}

export async function noteHasTagWithNormalizedName(
  noteId: string,
  tagName: string,
  noteOwnerUserId: string,
): Promise<boolean> {
  const normalized = normalizeTagName(tagName);
  if (!normalized) return false;

  const existing = await db
    .select({ name: Tags.name })
    .from(NoteTags)
    .innerJoin(Tags, eq(NoteTags.tagId, Tags.id))
    .where(and(eq(NoteTags.noteId, noteId), eq(Tags.userId, noteOwnerUserId)));

  return existing.some((t) => normalizeTagName(t.name) === normalized);
}

export async function removeNoteTagsByName(
  noteId: string,
  tagName: string,
  noteOwnerUserId: string,
): Promise<number> {
  const normalized = normalizeTagName(tagName);
  if (!normalized) return 0;

  const links = await db
    .select({ tagId: NoteTags.tagId, name: Tags.name })
    .from(NoteTags)
    .innerJoin(Tags, eq(NoteTags.tagId, Tags.id))
    .where(and(eq(NoteTags.noteId, noteId), eq(Tags.userId, noteOwnerUserId)));

  let removed = 0;
  for (const link of links) {
    if (normalizeTagName(link.name) !== normalized) continue;
    await db.delete(NoteTags).where(and(eq(NoteTags.noteId, noteId), eq(NoteTags.tagId, link.tagId)));
    removed++;
  }
  return removed;
}
