import type { APIRoute } from 'astro';
import { db, Tags, NoteTags, eq, and } from 'astro:db';
import { debug } from '@/utils/logger';

export const GET: APIRoute = async ({ request, locals }) => {
  // Restrict to development only
  if (import.meta.env.PROD) {
    return new Response(JSON.stringify({ error: 'Debug endpoints are not available in production' }), {
      status: 403,
      headers: { 'Content-Type': 'application/json' }
    });
  }

  try {
    const { userId } = locals.auth();
    
    if (!userId) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    const url = new URL(request.url);
    const noteId = url.searchParams.get('noteId');

    debug('Debug: Checking tags for note', { noteId, userId: userId?.substring(0, 10) + '...' });

    if (!noteId) {
      return new Response(JSON.stringify({ error: 'noteId parameter required' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // Check if tags exist for this note
    const tagsWithNote = await db
      .select({
        id: NoteTags.id,
        noteId: NoteTags.noteId,
        tagId: NoteTags.tagId,
        isAutoGenerated: NoteTags.isAutoGenerated,
        confidence: NoteTags.confidence,
        createdAt: NoteTags.createdAt,
        tag: {
          id: Tags.id,
          name: Tags.name,
          color: Tags.color,
          category: Tags.category,
          isSystem: Tags.isSystem
        }
      })
      .from(NoteTags)
      .innerJoin(Tags, eq(NoteTags.tagId, Tags.id))
      .where(and(eq(NoteTags.noteId, noteId), eq(Tags.userId, userId)));

    debug('Debug: Tags found for note', {
      noteId,
      tagCount: tagsWithNote.length
    });

    // Also check all tags for this user
    const allUserTags = await db
      .select()
      .from(Tags)
      .where(eq(Tags.userId, userId));

    debug('Debug: All user tags', {
      totalTags: allUserTags.length
    });

    return new Response(JSON.stringify({
      success: true,
      noteId,
      tagsForNote: {
        count: tagsWithNote.length,
        tags: tagsWithNote.map(t => ({
          name: t.tag.name,
          isAutoGenerated: t.isAutoGenerated,
          confidence: t.confidence
        }))
      },
      allUserTags: {
        count: allUserTags.length,
        tags: allUserTags.map(t => ({
          id: t.id,
          name: t.name,
          isSystem: t.isSystem
        }))
      }
    }), {
      status: 200,
      headers: {
        'Content-Type': 'application/json'
      }
    });
    
  } catch (error) {
    console.error('Debug: Error checking tags:', error);
    
    return new Response(JSON.stringify({
      success: false,
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined
    }), {
      status: 500,
      headers: {
        'Content-Type': 'application/json'
      }
    });
  }
};
